awslabs/llrt

README.md

The command "make release-x86" does not build

doc; fix make command

---

src/encoding/encoder.rs
tests/buffer.test.ts

Fixes: https://github.com/awslabs/llrt/issues/116
Changes b64 decoding to forgiving mode that ignores missing padding.

Fix Buffer.from base64 when padding is missing

---

README.md

*Description of changes:* I saw a missing apostrophe in the README while looking through (`llrt` looks very cool!), thought I'd open a quick PR to fix it.

Add missing apostrophe in README

---

src/process.rs

*Fixes #126*
Defines process.versions on the process global. Some nodejs packages (e.g. [pg-promise](https://github.com/vitaly-t/pg-promise/blob/master/lib/index.js#L11)) rely on it for feature detection.
My first ever rust pr. I looked into how to expose the quickjs & turbo version, but I'm afraid I don't understand the ecosystem well enough.

define process.versions

---

README.md

When I first received access to this project I was very pleased to see that the benchmarks measured round-trip request latency for a given cold start.
I don't believe this is common knowledge (as it surprised a number of folks when I [spoke about it at re:Invent](https://www.youtube.com/watch?t=1421&v=2EDNcPvR45w&feature=youtu.be)), so I believe a short description is helpful.
>By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
I agree!

[docs] - Add benchmark methodology section to Readme

---

README.md

This section still refers to MIT-0, while it seems the current license is now Apache-2.0.

Update license section in README

---

src/console.rs
src/encoding/mod.rs
src/main.rs
src/process.rs

Fixes: https://github.com/awslabs/llrt/issues/150
This will return higher resolution to the `process.hrtime.bigint()`. The "time basis" from node is slightly different where node uses an offset from a previous value (that seems to be inited from uptime) where as LLRT uses an start offset from startup time of the program. This change does not effect the behavior of timers as they are not based from unix epoch and should have nanosecond precision.

Fix process hr-time-res

---

src/vm.rs

I noticed duplicated `uuid` module definition
- removed the first occurrence of `uuid` module definition

Remove duplicate module definition

---

build.mjs

When importing the `SFNClient` from `@aws-sdk/client-sfn`, the runtime will throw an error: `client error (Connect)`.
This was occurring because the `addAwsSdkInitTask` function in the bootstrap was trying to connect to
`https://sfn.<region>.amazonaws.com` rather than `https://states.<region>.amazonaws.com`.
This change updates the service endpoint subdomain from `sfn` to `states`.

Update Step Functions service endpoint from sfn to states

---

README.md

The current Rollup plugins suggested are old. I updated to reference correct modules 🙂

docs: use the correct rollup plugins

---

src/crypto/mod.rs
tests/crypto.test.ts

closes #177 
I just stumbled upon this issue so let me try fix this 🙏 
I'm still not sure how should I validate the entire build, but at least I confirmed `crypto.randomBytes` returns a buffer locally.

Crypto.randomBytes returns a Buffer

---

src/json/mod.rs
src/json/stringify.rs

Fixes https://github.com/awslabs/llrt/issues/183
JSON serialization was switched from QuickJS built in to a custom implementation in 0.1.4. This yielded a 2x performance gain. A bug caused the key of any object with a `toJSON()` method to be written twice when present in a parent object.
This PR fixes the issue by removing the parent key from the serialization context.

Fix custom toJSON object JSON serialization.

---

src/http/headers.rs
tests/http.test.ts

closes #186 
I omitted [forEach's third argument `object`](https://developer.mozilla.org/en-US/docs/Web/API/Headers/forEach) for now because i'm not sure how to efficiently pass Headers object in each loop (without cloning btreemap), and also it's rarely used anyway.
I add [`keys` method](https://developer.mozilla.org/en-US/docs/Web/API/Headers/keys) as it was also missing.

keys and forEach method for Headers

---

CHANGELOG.md
shims/sdk-stream-mixin.js

Fixes https://github.com/awslabs/llrt/issues/191
Regression in S3 was introduced when returning fetch body as an object. This PR fixes that by returning `typedArray` from body

Fix S3 object read

---

README.md

On m1 Mac running `make release` fails on first attempt if user does not have `cmake` installed.
```
error: failed to run custom build command for `snmalloc-sys v0.3.4`
```

Update README.md - cmake is required for make release

---

src/fs/read_dir.rs

Fixes https://github.com/awslabs/llrt/issues/198
Should be named `isDirectory`

Change speling to is_directory

---

src/environment.rs
src/http/fetch.rs
src/main.rs
src/minimal_tracer.rs
src/net/mod.rs
src/security.rs
src/vm.rs

Connection pool idle timeout is not configured to 15s to reduce potential issues when server closing an unused connection while in flight after to long idling.

Extract environment and set connection pool idle timeout to 15s

---

src/http/url.rs
tests/http.test.ts

Adds username and password properties to URL per WHATWG spec https://url.spec.whatwg.org/#url
also adds canParse utility static method.
Adds testing, testing is basic cases since the underlying rust crate url, does much of the heavy lifting.

URL username password and canParse

---

fixtures/fs/readdir/readdir.js
fixtures/fs/readdir/recursive/readdir.js
src/fs/read_dir.rs
src/main.rs
src/path.rs
src/utils/io.rs
tests/unit/fs.test.ts

Issue fix #197
add recursive option for readdir
```js
fs.readdir('example', { recursive: true })
.then(res => {
console.log(res);
});
```

feat: add recursive option for readdir

---

src/fs/mkdir.rs
src/fs/mod.rs
src/js/@llrt/expect/jest-expect.ts
tests/unit/fs.test.ts
tests/unit/jest-expect.test.ts

Implement mkdir sync, fix an issue when using expect(...).rejects.toThrow in unit tests

Feat/implement mkdirSync

---

src/timers.rs

Avoids copying elements in list by instead taking callback reference and set timeout to 0 for scheduled removal on next timer tick

Optimize timer removal

---

.github/pull_request_template.md
.github/workflows/ci.yml
src/fs/read_dir.rs
src/main.rs
src/utils/io.rs

Cleanup DirectoryWalker & Remove warnings

Cleanup walkdir & fix warnings

---

API.md
src/fs/mkdir.rs
src/fs/mod.rs
src/fs/read_dir.rs
src/main.rs
src/utils/io.rs
tests/unit/fs.test.ts

Implemented readdirSync (https://nodejs.org/api/fs.html#fsreaddirsyncpath-options)
- [N/A] Updated documentation if needed ([API.md](API.md)/[README.md](README.md)/Other)

feat: implement readdirSync

---

API.md
src/fs/access.rs
src/fs/mod.rs
tests/unit/fs.test.ts

Implement [accessSync](https://nodejs.org/api/fs.html#fsaccesssyncpath-mode)

feat: implement accessSync

---

README.md

If you've cloned the repository before reading the building from source instructions, you might have missed the submodule required to build llrt.
This change adds information about the zstd submodule to the README.

Document git submodules

---

README.md
example/llrt-sam-container-image/hello-world/Dockerfile

Can't resolve https://github.com/awslabs/llrt/releases/download/latest/llrt-container-arm64
According to [Linking to the latest release](https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases#linking-to-the-latest-release),
the correct url is below.
https://github.com/awslabs/llrt/releases/latest/download/llrt-container-arm64
In addition, it works to build docker image with this.

fix: wrong a url of github release at the Dockerfile

---

API.md
src/fs/mkdir.rs
src/fs/mod.rs
tests/unit/fs.test.ts

https://github.com/awslabs/llrt/issues/249
Implemented mkdtempSsync

feat: implement [mkdtempSync]https://nodejs.org/api/fs.html#fsmkdtempsyncprefix-options)

---

src/json/escape.rs
src/json/mod.rs
src/json/stringify.rs

`undefined` values where not correctly handled by json_stringify

Fix JSON.stringify of undefined values

---

API.md
src/fs/mkdir.rs
src/fs/mod.rs
src/fs/rm.rs
tests/unit/fs.test.ts

feat: implement rmdirSync

---

README.md

- Add dependencies of Windows WSL2 in Building from source section
result of `make release-x64` and example of `llrt-container-x64` execution:

Update README.md - Add dependencies of Windows WSL2 in Building from source section

---

Makefile

- Fix `make release` in Windows WSL2 environment

Fix 'make release' in Windows WSL2 environment

---

API.md
src/fs/mod.rs
src/fs/stats.rs
src/fs/write_file.rs
tests/unit/fs.test.ts

Implement writeFileSync and statSync

feat: implement statSync, writeFileSync

---

build.mjs

- fix: [ERROR] No replacement found for "getRuntimeConfig" in runtimeConfig.shared.js
There is wrapper logic in `build.mjs` that injects AWS credentials and region parameters into `runtimeConfig.shared.js` in `@aws-sdk`.
However, we found that there are `runtimeConfig.shared.js` in `@aws-sdk` that do not follow the following rules.
@aws-sdk/client-s3/dist-es/runtimeConfig.shared.js:
```javascript
// getRuntimeConfig is included in the code, so it is successfully bundled.
...
export const getRuntimeConfig = (config) => {
return {
apiVersion: "2006-03-01",
base64Decoder: config?.base64Decoder ?? fromBase64,
base64Encoder: config?.base64Encoder ?? toBase64,
disableHostPrefix: config?.disableHostPrefix ?? false,
endpointProvider: config?.endpointProvider ?? defaultEndpointResolver, …
```

fix: [ERROR] No replacement found for "getRuntimeConfig"

---

API.md
build.mjs
src/console.rs
src/vm.rs
tests/unit/console.test.ts

Added the possibility to create a Console object (but does not support custom steams for now)

feat: implement Console object with import node:console or console

---

README.md

in README.md
- Correction of artifact name `llrt-lambda-x86.zip` -> `llrt-lambda-x64.zip`

typo: Correction of artifact name

---

README.md
package.json
src/js/@llrt/test.ts

Refs: #240
As discussed, removed `assert` support to make sure jest/chai assertions are used instead (using vitest)
- [N/A] Created unit tests in `tests/unit` and/or in Rust for my feature if needed

chore: remove `assert` support to make sure jest/chai is used instead.

---

API.md
Cargo.lock
Cargo.toml
build.mjs
src/crypto/mod.rs
tests/unit/crypto.test.ts

Implement randomInt with support for min and max value only so that it can be used with powertools.

feat: implement randomInt in crypto module

---

API.md
build.mjs
src/http/mod.rs
src/http/url.rs
src/main.rs
src/url.rs
src/vm.rs
tests/unit/http.test.ts
yarn.lock

https://github.com/awslabs/llrt/issues/214
Adopt WHATWG URL Spec for ESM import syntax: https://nodejs.org/api/url.html#new-urlinput-base
> The URL constructor is accessible as a property on the global object. It can also be imported from the built-in url module
```typescript
import { URL, URLSearchParams } from "url";
```
Also noticed there was a bug in `URL.canParse()` and fixed it.
Original ticket: https://github.com/awslabs/llrt/issues/195 requested `URL.parse` however this has been deprecated, https://nodejs.org/api/url.html#urlparseurlstring-parsequerystring-slashesdenotehost,
>url.parse() uses a lenient, non-standard algorithm for parsing URL strings. It is prone to security issues such as [host name spoofing](https://hackerone.com/reports/678487) and incorrect handling of …

init url module

---

API.md
build.mjs
src/http/fetch.rs
src/main.rs
src/navigator.rs
src/vm.rs
tests/unit/navigator.test.ts

[The Minimum Common Web Platform API](https://common-min-api.proposal.wintercg.org/) is being considered at WinterCG.
I implemented one of the APIs, `globalThis.navigator.userAgent`.
This is my first time coding in the rust language, so I will promote it as a draft version.
Please point out if it does not follow `llrt` or `rust` conventions.

feat: implement globalThis.navigator.userAgent

---

src/events.rs
tests/unit/events.test.ts

https://github.com/awslabs/llrt/issues/248
Adds an implementation for `AbortController` with stubbed methods for `AbortSignal` which would have the actual event aborting implementation.  This implementation attempts to follow the specification found here https://dom.spec.whatwg.org/#ref-for-dom-abortcontroller-abortcontroller%E2%91%A0

Add AbortController implementation

---

.gitignore

- Adding `llrt` and `bootstrap` to `.gitignore` prevents accidental commits after unzipping a zip created with `make release` or `make release-*` and checking local behavior.
- [n/a] Created unit tests in `tests/unit` and/or in Rust for my feature if needed
- [n/a] Ran `make fix` to format JS and apply Clippy auto fixes
- [n/a] Made sure my code didn't add any additional warnings: `make check`
- [n/a] Updated documentation if needed ([API.md](API.md)/[README.md](README.md)/Other)

chore: add llrt binaries to .gitignore

---

src/vm.rs
tests/unit/require.test.ts

Fix an issue where require would not work in LLRT when the `node:` prefix was used
- [N/A] Updated documentation if needed ([API.md](API.md)/[README.md](README.md)/Other)

fix an issue where require would not work in LLRT when the `node:` prefix was used

---

src/json/stringify.rs
tests/unit/json.test.ts

Fixes https://github.com/awslabs/llrt/issues/314
Fix JSON.stringify if undefined values at any object possition

Fix undefined values during json stringify

---

API.md
build.mjs
src/main.rs
src/performance.rs
src/process.rs
src/vm.rs
tests/unit/performance.test.ts

[The Minimum Common Web Platform API](https://common-min-api.proposal.wintercg.org/) is being considered at WinterCG.
I have implemented the following several APIs.
- globalThis.performance.timeOrigin
- globalThis.performance.now()

feat: implement globalThis.performance API

---

src/performance.rs
tests/unit/performance.test.ts

[The Minimum Common Web Platform API](https://common-min-api.proposal.wintercg.org/) is being considered at WinterCG.
In this context, the performance API is being studied in the [High Resolution Time](https://www.w3.org/TR/hr-time-3/) Team.
We believe that implementing toJSON() will also be compliant with this draft.
- globalThis.performance.toJSON()

feat: Implement globalThis.performance.toJSON()

---

src/fs/read_dir.rs
src/fs/stats.rs
src/utils/io.rs
tests/unit/fs.test.ts

Symlinks may cause errors when reading dir and should not be followed. This PR fixes `readdir` call

Fix fs readdir for symlinks

---

rustfmt.toml
src/child_process.rs
src/console.rs
src/crypto/mod.rs
src/crypto/sha_hash.rs
src/events.rs
src/fs/read_dir.rs
src/http/body.rs
src/http/response.rs
src/json/parse.rs
src/json/stringify.rs
src/main.rs
src/net/socket.rs
src/number.rs
src/path.rs
src/runtime_client.rs
src/stream/readable.rs
src/utils/clone.rs
src/utils/object.rs
src/vm.rs
src/xml.rs

Thid PR adds rustfmt.toml, currently the following rules were added: 
- ` fn_params_layout = "Tall"` : https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=#fn_params_layout
- `edition = "2021"` https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=edition#edition
-  `match_block_trailing_comma = true` https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=#match_block_trailing_comma
There are some rules that may be convenient to run like:
- https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=group#imports_granularity
- https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=group#group_imports
But they are unstable and can only be run with nightly.
I will run `make fix` when reviewers agree on the rules.

Add rustfmt.toml to mantain format consistency

---

build.mjs
src/exceptions.rs
src/main.rs
src/vm.rs
tests/unit/exceptions.test.ts

Fixes #330  
[The Minimum Common Web Platform API](https://common-min-api.proposal.wintercg.org/) is being considered at WinterCG.
This PR provides [DOMException()](https://developer.mozilla.org/en-US/docs/Web/API/DOMException), which is not yet implemented in `llrt`.
The unit test with javascript seems to be working well, but we have not yet implemented the return of exceptions from rust to javascript.
events.rs:
```rust
let abort_exception = Exception::from_value("AbortError".into_js(&ctx)?)?; // TODO: AbortError DOMException
```
```rust
let timeout_exception = Exception::from_value("TimeoutError".into_js(&ctx)?)?; // TODO: Timeout DOMException
```
What implementation is needed to eliminate this problem?
Any reference to implementations or sample code in already existing projects would …

feat: Implement DOMException()

---

Makefile

(skipped issue; will open if desired.)
add `Makefile` target to redirect `llrt-darwin-x86_64.zip` to `llrt-darwin-x64.zip`, mirroring the same logic used for linux. It's a one-line Makefile change, so it shouldn't impact any of the code.

add x86_64 > x64 mapping for darwin

---

.github/workflows/build.yml
API.md
src/events.rs
src/exceptions.rs
src/http/fetch.rs
src/http/request.rs
src/http/response.rs
src/utils/mc_oneshot.rs
src/utils/mod.rs
tests/unit/events.test.ts
tests/unit/fetch.test.ts
tests/unit/http.test.ts

Fixes https://github.com/awslabs/llrt/issues/182
Allow to pass an AbortSignal as an option to a request. Ensure that only AbortSignal types are allowed.

Implement Request#signal.

---

llrt_core/src/modules/http/fetch.rs

- Fixed a failure to return the last url in `response.url` after being redirected by `fetch`. (See also. [Fetch Standard#responses](https://fetch.spec.whatwg.org/#responses))

fix: wrong response.url in fetch()

---

llrt_core/src/environment.rs
llrt_core/src/modules/net/mod.rs

- If the environment variable `LLRT_HTTP_VERSION` is not present, the connection is established with `http/2`. (This is the default behavior.)
- If the environment variable `LLRT_HTTP_VERSION` is set to `1.1`, the connection is established with `http/1.1`.
- If the environment variable `LLRT_HTTP_VERSION` is set to a value other than `1.1` (for example, `5`), the connection is established with `http/2`.

feat: Support for http/2

---

.github/workflows/ci.yml
Makefile
build.mjs
llrt_core/build.rs
llrt_core/src/vm.rs
tests/e2e/README.md

from commit message:
Because build.rs depends on the bundle/ directory, whenever it also writes into it, the directory's timestamp is updated. This leads Cargo to always consider it outdated and re-run build.rs every time.
To fix this, separate the inputs to build.rs (the JS files) into a separate directory, bundle/js/, and move the compiled .lrt files to bundle/lrt/. This will keep their timestamps separate.

fix: Avoid re-running build.rs on every build, even when nothing changed

---

Cargo.lock
llrt_core/Cargo.toml
llrt_core/src/modules/http/fetch.rs
llrt_core/src/modules/http/response.rs

- Implementation of decompression in fetch()
Supported Encodings: gzip, deflate, br, zstd
content-encoding.js:
```javascript
const main = async () => {
try {
const response = await fetch('https://www.meta.com/', {headers: {"accept-encoding": process.argv[2]}});
console.log(response.headers.get('content-encoding'));
const responseText = await response.text();
console.log('vvv');
console.log(responseText.substring(0, 100));
console.log('^^^');
} catch(e) {
console.log(e);
}
}
main();
```
1. accept-encoding: `zstd`
```
shinya@MBA2022M2 llrt-test % ./llrt content-encoding.js zstd   
zstd
vvv
<!DOCTYPE html><html id="facebook" class="_a4ch _aber" lang="ja" dir="ltr"><head><link data-default-
^^^
```
2. accept-encoding: `br`
```
shinya@MBA2022M2 llrt-test % ./llrt content-encoding.js br  
br …
```

feat: Implementation of decompression in fetch()

---

llrt_core/src/module_builder.rs
llrt_core/src/modules/crypto/mod.rs
tests/unit/crypto.test.ts

Fixed that `crypto` was only available as a module.
See also. https://runtime-compat.unjs.io/#Crypto

feat: expose globalThis.crypto

---

build.mjs
llrt_core/src/modules/console.rs
llrt_core/src/modules/util.rs
tests/unit/console.test.ts

Fix an issue with console.log when using format pattern, implement util.format

Implement issue 302, fix an issue with console.log

---

API.md
llrt_core/src/modules/http/url_search_params.rs
tests/unit/http.test.ts

Add the following methods/properties to improve the compliance of URLSearchParams.
- URLSearchParams.size
- URLSearchParams.keys()
- URLSearchParams.forEach()

feat: Improved compliance of URLSearchParams

---

llrt_core/src/modules/http/request.rs
tests/unit/http.test.ts

Add the following methods/properties to improve the compliance of `Request` Object.
- Request.bodyUsed
- Request.mode
- Request.cache
- Request.text()
- Request.json()
- Request.arrayBuffer()

feat: Improved compliance of Request Object

---

llrt_core/src/modules/http/response.rs
tests/unit/http.test.ts

Add the following methods to improve the compliance of `Response` Object.
- Response.error() static method
- Response.json() static method
- Response.redirect() static method

feat: Improved compliance of Response Object

---

llrt_core/src/modules/http/headers.rs
tests/unit/http.test.ts

Fixes #374 
- Improved management of `set-cookie` in `Headers` class
- implementation of `Headers.getSetCookie()`
~In the case of MultipleValue, it should be possible to retrieve values of type String with the same key one at a time, but it conflicts with `into_js` own implementation and retrieves comma-separated values at a time.~
The reason was that the `Object::map_to_entries()` that `js_entries()` was calling was not able to support `HeaderValue`.
We did not want to control `HeaderValue` outside of the `Headers` class, so we implemented our own `js_entries()`.
<details><summary>reproduction.js</summary>
```javascript
const headers = new Headers();
headers.append("Set-Cookie", "AAA=123; expires=Sun, 10-Nov-2024 12:29:35 GMT; path=/; domain=.sample.com; HttpOnly"); …
```

feat: Improved management of set-cookie in Headers class

---

llrt_core/src/modules/http/url.rs
tests/unit/http.test.ts

Add the following methods to improve the compliance of `URL` Object.
- URL.toJSON()

feat: Improved compliance of URL object

---

llrt_core/src/modules/http/url_search_params.rs
tests/unit/http.test.ts

https://github.com/awslabs/llrt/issues/396
Append value if not present

Fix url search params for non-existing keys

---

llrt_core/src/modules/http/request.rs
llrt_core/src/modules/http/response.rs
tests/unit/http.test.ts

Add the following methods to improve the compliance of `request` and `response` Object.
See also. https://fetch.spec.whatwg.org/#dom-body-bytes
- request.bytes()
- response.bytes()

feat: Improved compliance of request and response

---

llrt_core/src/runtime_client.rs

Related #406 
Fix `make check` no longer passes.
```bash
% make check
cargo clippy --all-targets --all-features -- -D warnings
Compiling llrt_core v0.1.14-beta (/Users/shinya/Workspaces/llrt/llrt_core)
error: the item `console` is imported redundantly
--> llrt_core/src/runtime_client.rs:470:13
|
6   | use crate::modules::console;
|     ----------------------- the item `console` is already imported here
...
470 |         use crate::modules::console;
|             ^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `-D unused-imports` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(unused_imports)]`
error: the item `Rest` is imported redundantly
--> llrt_core/src/runtime_client.rs:471:13
|
23  | use rquickjs::function::{Rest, This};
|                          ---- the item `Rest` is …
```

fix: make check broken

---

llrt_core/src/modules/http/headers.rs
tests/unit/http.test.ts

In the `get()` method of the `Headers` object, `undefined` is returned when a non-existent key is specified.
```shell
% ./llrt -e "console.log(new Headers().get('aaa'));"
undefined
```
Normally, `null` should be returned.
https://developer.mozilla.org/en-US/docs/Web/API/Headers/get
> The get() method of the [Headers](https://developer.mozilla.org/en-US/docs/Web/API/Headers) interface returns a byte string of all the values of a header within a Headers object with a given name. If the requested header doesn't exist in the Headers object, it returns null.

fix: get method does not return null

---

llrt_core/src/modules/http/blob.rs
llrt_core/src/modules/http/body.rs
tests/unit/http.test.ts

Add the following methods to improve the compliance of `Blob` and `Body` Object.
- Blob.bytes()
https://www.w3.org/TR/FileAPI/#bytes-method-algo
- Body.bytes()
https://fetch.spec.whatwg.org/#dom-body-bytes

feat: Improved compliance of Blob and Body

---

llrt_core/Cargo.toml
llrt_core/benches/numbers.rs
llrt_core/src/lib.rs
llrt_core/src/modules/console.rs
llrt_core/src/modules/xml.rs
llrt_core/src/number.rs

Reducing allocations in XML parsing & number formatting

perf: Misc string perf improvements

---

llrt_core/src/modules/encoding/text_encoder.rs
tests/unit/encoding.test.ts

Add the following methods to improve the compliance of Encoding API.
- TextEncoder.encodeInto()

feat: Improved compliance of TextEncoder

---

llrt_core/src/module_builder.rs
llrt_core/src/modules/navigator.rs
llrt_core/src/modules/performance.rs
tests/unit/navigator.test.ts

Currently, the following functions are provided as modules in LLRT.
- Performance
- Navigator
This is a module that is not compatible with node.js (or has a name that does not exist) and should stop being offered as a module before it is misused.
In fact, the following code will result in a `MODULE_NOT_FOUND` error in node.js.
```shell
% node -e "const a = require('navigator');"  
node:internal/modules/cjs/loader:1148
throw err;
^
Error: Cannot find module 'navigator'
Require stack:
- /Users/shinya/Workspaces/llrt-test/[eval]
at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
at Module._load (node:internal/modules/cjs/loader:986:27)
at Module.require (node:internal/modules/cjs/loader:1233:19)
at require (node:internal/modules/helpers:179:18)
at [eval]:1:11
at …
```

Fix: Removed several module offerings

---

README.md
build.mjs
package.json
yarn.lock

This PR adds a package to streamline pre-signed access to Amazon S3.
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-s3-presigned-post/

feat: include @aws-sdk/s3-presigned-post

---

build.mjs
shims/smithy-abort-controller.js

Many `@aws-sdk` packages directly or indirectly depend on `@smithy/abort-controller`.
But if you check the implementation of `@smithy/abort-controller`, `AbortController` and `AbortSignal` are just defined.
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-smithy-abort-controller/
https://github.com/smithy-lang/smithy-typescript/tree/main/packages/abort-controller/src
LLRT already provides these classes as native objects of Rust, so there is no need for them.
This PR replaces the `@smithy/abort-controller` import statement with an empty javascript file so that the native implementation can be used.
We also believe that replacing with native implementation will lead to some performance improvement.
_By submitting this pull request, I confirm that you can use, modify, copy, …

perf: replacement of @smithy/abort-controller

---

llrt_core/src/modules/http/url.rs
llrt_core/src/modules/http/url_search_params.rs

Minor adjustments to URL and URLSearchparams.
`delete` and `has` methods are no longer cloning, checking for `undefined` and converting to string for each iteration. Some shared conversion logic is moved into a function
`from_str` only adds a "?" if not already there.
@stephencroberts please verify

minor URL & URLSearchParams adjustments

---

API.md
build.mjs
llrt_core/src/module_builder.rs
llrt_core/src/modules/encoding/mod.rs
llrt_core/src/modules/llrt/hex.rs
llrt_core/src/modules/llrt/mod.rs
llrt_core/src/modules/mod.rs
shims/util-hex-encoding.js
tests/unit/encoding.test.ts

While reviewing the module implementation, I noticed that a `hex` module is provided that does not exist in the standard node.js API.
```shell
% node -e "const a = require('hex');"
node:internal/modules/cjs/loader:1148
throw err;
^
Error: Cannot find module 'hex'
Require stack:
- /Users/shinya/Workspaces/llrt-test/[eval]
at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
at Module._load (node:internal/modules/cjs/loader:986:27)
at Module.require (node:internal/modules/cjs/loader:1233:19)
at require (node:internal/modules/helpers:179:18)
at [eval]:1:11
at runScriptInThisContext (node:internal/vm:209:10)
at node:internal/process/execution:118:14
at [eval]-wrapper:6:24
at runScript (node:internal/process/execution:101:62)
at evalScript …
```

fix: rename hex module to @llrt/hex

---

llrt_modules/src/modules/fs/mod.rs

-  Also exporting constants on the sync fs API

Export constants on sync fs API

---

API.md
README.md
build.mjs
llrt_core/src/module_builder.rs
llrt_core/src/modules/crypto/mod.rs
llrt_core/src/modules/llrt/mod.rs
llrt_core/src/modules/llrt/uuid.rs
llrt_core/src/modules/mod.rs
llrt_core/src/runtime_client.rs
tests/unit/uuid.test.ts

Fixed #472 
The `uuid` module implemented as a native module in LLRT is intended to speed up the bundled SDK in LLRT. At this time, it is not fully compatible with the `uuid` in the node.js package.
This PR is a renaming so that it can provide functionality in its own namespace.
In addition, we have decided to include information on alias in the README so that you can understand it and use it in your own applications.
I am not confident in the writing of the README because I am not a resident of an English-speaking country. I would appreciate it if someone could correct me. :)

fix: rename uuid module to llrt:uuid

---

Cargo.lock
README.md
llrt_core/Cargo.toml
llrt_core/src/environment.rs
llrt_core/src/modules/http/fetch.rs
llrt_core/src/modules/net/mod.rs
llrt_core/src/runtime_client.rs

#469 
Adds support for extra CA certificates, mirroring the NODE_EXTRA_CA_CERTS functionality in Node.js. This is utilizing the rustls-pemfile crate for PEM file parsing.
The environment variable `LLRT_EXTRA_CA_CERTS` is used to configure the path to the extra certificates file.
I didn't see any relevant tests for this module. I'm happy to add them if required.

add support for extra ca certs

---

.github/workflows/build-modules.yml
.github/workflows/ci.yml
Cargo.lock
llrt_core/Cargo.toml
llrt_core/src/modules/mod.rs
llrt_core/src/modules/process.rs
llrt_modules/Cargo.toml
llrt_modules/src/modules/fs/file_handle.rs
llrt_modules/src/modules/fs/mkdir.rs
llrt_modules/src/modules/fs/mod.rs
llrt_modules/src/modules/fs/open.rs
llrt_modules/src/modules/fs/stats.rs
llrt_modules/src/modules/mod.rs
llrt_modules/src/modules/os.rs
llrt_modules/src/modules/os/mod.rs
llrt_modules/src/modules/os/unix.rs
llrt_modules/src/modules/os/windows.rs
llrt_modules/src/modules/path.rs
llrt_modules/src/modules/process.rs

-  Added windows support for the modules
- Move OS module and added windows support
- Added CI for modules for windows, macos and linux (x86 only, it is sufficient)

Windows support for modules + move os 

---

llrt_core/src/modules/http/fetch.rs
llrt_core/src/modules/http/mod.rs
llrt_core/src/modules/net/mod.rs
llrt_core/src/modules/net/server.rs
llrt_core/src/modules/net/socket.rs
llrt_core/src/runtime_client.rs

To prepare for future improvements, the `net` module has been divided as follows.
- `Server` class (server.rs)
- `Socket` class (socket.rs)
- Common Implementation (mod.rs)
In addition, definitions such as `HTTP_CLIENT` have been moved to appropriate locations.

refactor: organize net module implementation

---

API.md
llrt_core/src/modules/net/mod.rs
llrt_core/src/vm.rs

Fixed #482 
This PR will allow the correct output of the content of errors during module initialization.
After the revision:
```shell
% LLRT_NET_DENY=/ ./llrt -e 'console.log("123")'
ReferenceError: LLRT_NET_DENY env contains an invalid URI
```

fix: throwing exceptions during module initialization

---

Cargo.lock
llrt_core/Cargo.toml

Removes a few dependencies for `llrt_core` that aren't used.

chore(llrt_core): remove unused deps

---

build.mjs
llrt_core/src/modules/llrt/xml.rs
llrt_utils/src/bytes.rs
shims/@smithy/split-stream.js

Fixes latest S3 AWS SDK API & a bug with `get_bytes` with large offset from array buffer. 

Fix new S3 API and bytes with offset

---

Cargo.lock
llrt_core/src/modules/encoding/mod.rs
llrt_modules/Cargo.toml
llrt_modules/README.md
llrt_modules/src/modules/buffer.rs
llrt_modules/src/modules/mod.rs
llrt_utils/Cargo.toml
types/buffer.d.ts

- We dont need a separate feature flag for performance, it is part of the same module for node.
- Flag should respect the naming convention
- New modules should be added to the README
- Dependencies should be marked optional and enabled in feature flag whenever possible
- Move the `atob` and `btoa` legacy methods to buffer
Once we have a better module trait, we should merge `performance.rs` and `perf_hooks.rs`.

Cleanup and minor improvements

---

Cargo.lock
llrt_core/src/module_builder.rs
llrt_core/src/modules/mod.rs
llrt_core/src/vm.rs
llrt_modules/Cargo.toml
llrt_modules/src/lib.rs
llrt_modules/src/modules/mod.rs
llrt_modules/src/modules/os/mod.rs
llrt_modules/src/modules/perf_hooks.rs
llrt_modules/src/modules/performance.rs
llrt_modules/src/modules/process.rs
llrt_modules/src/sysinfo.rs
llrt_modules/src/time.rs
types/process.d.ts

- Remove `os` dependency on `process`
- Remove `chrono` (using `SystemTime`)
- Remove `performance` (merged into `perf_hooks`)
- Rework time to be independent of `perf_hook`
- Switched `TIME_ORIGIN` to an `AtomicU64` and removed casting (ensuring i686 works correctly) 

Rework time management & remove inter module dependency

---

llrt_core/Cargo.toml
llrt_core/src/modules/llrt/uuid.rs
tests/unit/uuid.test.ts

Closes #485 
Implement the following methods on the `llrt:uuid` package:
- uuid.MAX
- uuid.v1ToV6()
- uuid.V6()
- uuid.v6ToV1()
- uuid.V7()
The goal is to achieve greater compatibility with the existing Node.js package: https://github.com/uuidjs/uuid

Implement uuid.MAX, uuid.v1ToV6(), uuid.V6(), uuid.v6ToV1(), uuid.V7()

---

API.md
Cargo.lock
README.md
build.mjs
llrt_core/src/module_builder.rs
llrt_core/src/modules/mod.rs
llrt_modules/Cargo.toml
llrt_modules/README.md
llrt_modules/src/modules/mod.rs
llrt_modules/src/modules/zlib.rs
tests/unit/zlib.test.ts
types/index.d.ts
types/zlib.d.ts

Implement a portion of the Node.js zlib module ([Convenience methods](https://nodejs.org/api/zlib.html#convenience-methods)).
It is still rough around the edges at this point and some TODOs remain.
- ~Need to support more than just Brotli.~
All except unzip/unzipSync are now supported.
- ~Options also need to be supported as much as possible.~
For the time being, only the compression level has been addressed.
- ~Types/Tests/Docs also.~
All have been addressed.

feat: implement zlib module

---

llrt_core/build.rs

There will be escape problems on the Windows platform
```
("llrt-chunk-sdk-LPGTTHJP.js", include_bytes!("..\../bundle/lrt\llrt-chunk-sdk-LPGTTHJP.lrt")),
```

llrt_core: path separators in bytecode_cache files use Linux style

---

CHANGELOG.md
Cargo.lock
llrt/Cargo.toml
llrt_core/Cargo.toml
llrt_modules/Cargo.toml
llrt_utils/Cargo.toml

Prepare v0.2.0-beta

---

llrt_core/src/modules/timers.rs
tests/unit/timers.test.ts

The delay parameter is optional and can be negative.

llrt_core: delay should be optional

---

README.md
build.mjs
example/functions/build.mjs
example/infrastructure/tsconfig.json
example/llrt-sam/hello-world/tsconfig.json
example/llrt-sam/template.yaml
tsconfig.json

The target version has been revised as ES2023 is now supported in LLRT 0.2.0-beta.

chore: Correction of target version

---

Makefile

Fixed an argument error in hyperfine when running `make bench`.
Before:
```shell
% make bench
hyperfine -N --warm64up=100 "node fixtures/hello.js" "deno run fixtures/hello.js" "bun fixtures/hello.js" "./target/release/llrt fixtures/hello.js" "qjs fixtures/hello.js"
error: unexpected argument '--warm64up' found
tip: a similar argument exists: '--warmup'
Usage: hyperfine -N --warmup <NUM> <command>...
For more information, try '--help'.
make: *** [bench] Error 2
```
After:
```shell
% make bench
#cargo build -r
hyperfine -N --warmup=100 "node fixtures/hello.js" "deno run fixtures/hello.js" "bun fixtures/hello.js" "./target/release/llrt fixtures/hello.js" "qjs fixtures/hello.js"
Benchmark 1: node fixtures/hello.js
Time (mean ± σ):      23.4 ms ±   0.4 ms    [User: 19.7 ms, System: 2.8 ms] …
```

fix: hyperfine argument error

---

Cargo.lock
llrt/Cargo.toml
llrt/src/main.rs

In general, mimalloc has better performance

use mimalloc on windows

---

llrt_core/benches/json.rs
llrt_core/benches/numbers.rs
llrt_core/src/bytecode.rs
llrt_core/src/environment.rs
llrt_core/src/json/parse.rs
llrt_core/src/lib.rs
llrt_core/src/modules/crypto/crc32.rs
llrt_core/src/modules/crypto/md5_hash.rs
llrt_core/src/modules/crypto/mod.rs
llrt_core/src/modules/crypto/sha_hash.rs
llrt_core/src/modules/encoding/text_decoder.rs
llrt_core/src/modules/http/body.rs
llrt_core/src/modules/http/fetch.rs
llrt_core/src/modules/http/request.rs
llrt_core/src/modules/http/response.rs
llrt_core/src/modules/llrt/hex.rs
llrt_core/src/modules/llrt/uuid.rs
llrt_core/src/modules/llrt/xml.rs
llrt_core/src/modules/mod.rs
llrt_core/src/modules/util.rs
llrt_core/src/vm.rs
llrt_modules/src/modules/buffer.rs
llrt_modules/src/modules/fs/write_file.rs
llrt_modules/src/modules/zlib.rs
llrt_modules/src/stream/writable.rs
llrt_utils/src/bytes.rs
llrt_utils/src/encoding.rs
llrt_utils/src/error_messages.rs
llrt_utils/src/lib.rs

Introduces `ObjectBytes` util as a replacement for `get_bytes`. `ObjectBytes` is created from any JS value and owns that value as its true type (for example a `TypedArray` or `ArrayBuffer`). Since it owns its data it can also return a shared slice or Cow, leading to reduced copies for buffer based data types. This should increase performance and lower memory as less data is copied/duplicated/allocated.

perf: Reduced copying of bytes from objects such as ArrayBuffer or TypedArrays

---

llrt_core/build.rs
llrt_core/src/vm.rs

Cargo doesn't like when generated rust files are put in the `src` directory. This PR moves them to `OUT_DIR` environment (automatically set by cargo)

fix: Place generated files in OUT_DIR

---

llrt_core/src/json/stringify.rs
llrt_core/src/modules/console.rs
llrt_core/src/modules/http/headers.rs
llrt_core/src/modules/http/mod.rs
llrt_core/src/modules/http/request.rs
llrt_core/src/modules/http/url.rs
llrt_core/src/modules/http/url_search_params.rs
llrt_core/src/utils/clone.rs
llrt_core/src/vm.rs

Uses `unchecked_unwrap` where safe to do. Also improves some error handling.

Use unchecked_unwrap where safe

---

llrt_core/src/module_builder.rs
llrt_core/src/modules/events/abort_signal.rs
llrt_core/src/modules/mod.rs
llrt_core/src/modules/timers.rs
llrt_core/src/vm.rs
llrt_modules/Cargo.toml
llrt_modules/src/modules/mod.rs
llrt_modules/src/modules/timers.rs
llrt_utils/src/ctx.rs
tests/unit/console.test.ts

Use dynamic sleep instead of fixed for timer & interval sleeps. This significantly reduces wakes in the async scheduler since timers are very likely to be above 4ms (previous min value).

perf: Dynamic timer sleep

---

llrt_modules/src/modules/fs/open.rs
llrt_modules/src/modules/net/socket.rs
tests/unit/socket.test.ts

Fixes: https://github.com/awslabs/llrt/pull/536#issuecomment-2283467669
Make sure socket is really closed before trying to send to it. Process is expected to crash with an exception if no error handler is attached to the incoming socket.

fix: socket.destroy() & broken test

---

types/package.json

When installing `NPM` packages through PNPM or other monorepo solutions the package.json errors with:
```sh
 ERR_PNPM_SPEC_NOT_SUPPORTED_BY_ANY_RESOLVER  @definitelytyped/eslint-plugin@0.1,17 isn't supported by any available resolver.
```
This fixes the `package.json` so that it has the correct version as the one installed has a `,` instead of a `.` for a version number.
- [❌] Created unit tests in `tests/unit` and/or in Rust for my feature if needed
- [❌] Ran `make fix` to format JS and apply Clippy auto fixes
- [❌] Made sure my code didn't add any additional warnings: `make check`
- [❌] Added relevant type info in `types/` directory
- [❌] Updated documentation if needed ([API.md](API.md)/[README.md](README.md)/Other)
_By submitting this pull request, I confirm that you can use, modify, …

Fixes: @definitelytyped/eslint-plugin@0.1,17 isn't supported by any available resolver.

---

llrt_core/build.rs
llrt_core/src/modules/llrt/xml.rs
llrt_core/src/vm.rs
llrt_modules/src/modules/child_process.rs
llrt_modules/src/modules/crypto/crc32.rs
llrt_modules/src/modules/crypto/mod.rs
llrt_modules/src/modules/events/custom_event.rs
llrt_modules/src/modules/fs/read_dir.rs
llrt_modules/src/modules/fs/rm.rs
llrt_modules/src/modules/net/socket.rs
llrt_modules/src/stream/readable.rs
llrt_modules/src/stream/writable.rs

chore: remove unused ctx params

---

llrt_core/src/modules/encoding/text_decoder.rs
llrt_core/src/modules/llrt/hex.rs
llrt_core/src/modules/llrt/xml.rs
llrt_core/src/vm.rs
llrt_modules/src/modules/crypto/crc32.rs
llrt_modules/src/modules/crypto/md5_hash.rs
llrt_modules/src/modules/crypto/mod.rs
llrt_modules/src/modules/crypto/sha_hash.rs
llrt_modules/src/modules/fs/write_file.rs
llrt_modules/src/modules/zlib.rs
llrt_utils/src/bytes.rs

- We organized the existing code by implementing `FromJs` for `ObjectBytes`.

refactor: Improvement of ObjectBytes by implementing FromJs

---

llrt_modules/src/modules/buffer.rs
tests/unit/buffer.test.ts

Buffer.subarray implementation.

Buffer subarray

---

types/buffer.d.ts

https://github.com/awslabs/llrt/pull/559#issuecomment-2319564485
- Buffer typing has been added and reorganized.
- I have confirmed that the example code given in the comments works approximately (though a little less confidently) within the scope of the current implementation.

refactor: typing for buffer

---

llrt_core/src/modules/http/fetch.rs
llrt_core/src/modules/http/request.rs
llrt_core/src/modules/http/response.rs
tests/unit/fetch.test.ts

Closed #565
Support for `data: urls`(https://fetch.spec.whatwg.org/#data-urls) has been added.
Sample 1:
```javascript
// data-url1.js
const s = "hello"
const base64 = Buffer.from(s).toString("base64");
const dataURIPrefix = "data:application/octet-stream;base64,";
const url = dataURIPrefix + base64;
const resp = await fetch(url);
const buf = await resp.arrayBuffer();
const str = Buffer.from(buf).toString("ascii");
console.log(str === s);
```
```shell
% llrt data-url1.js
true
```
Sample 2: The source of the base64 string is, https://www.rfc-editor.org/rfc/rfc2397
```javascript
// data-url2.js
import fs from 'fs';
const imgUrl = "data:image/gif;base64,R0lGODdhMAAwAPAAAAAAAP///ywAAAAAMAAwAAAC8IyPqcvt3wCcDkiLc7C0qwyGHhSWpjQu5yqmCYsapyuvUUlvONmOZtfzgFzByTB10QgxOR0TqBQejhRNzOfkVJ+5YiUqrXF5Y5lKh …
```

feat(fetch): support data: URLs

---

build.mjs

Fix regression introduced by https://github.com/awslabs/llrt/pull/547 as invalid services names where eagerly added to connection init 

fix: AWS SDK connection init

---

types/timers.d.ts

Add typescript for timers. Added them to global since this is like expected to be there.

Add typing for timers

---

llrt_modules/src/modules/os/mod.rs
llrt_modules/src/modules/os/unix.rs
llrt_modules/src/modules/os/windows.rs
types/os.d.ts

Add os.EOL
https://nodejs.org/api/os.html#oseol

os: add EOL

---

llrt_core/src/json_loader.rs
llrt_core/src/lib.rs
llrt_core/src/vm.rs
tests/unit/import.test.ts
tests/unit/require.test.ts

Support require json files
```js
console.log( require('package.json') )
```

support require json file

---

llrt_modules/src/modules/timers.rs
tests/unit/timers.test.ts

Accept any parameter for setTimeout. None numeric values will just be ignored.

Allow any value for clearTimeout

---

llrt_core/src/module_builder.rs
llrt_core/src/modules/http/mod.rs
llrt_modules/src/modules/url/mod.rs

- Moved the init from http to url to keep things contain (also the module didn't work otherwise because it needs the global to be set)

Add init to url

---

llrt_core/src/json/stringify.rs
tests/unit/json.test.ts

keys containing functions or constructors where not ignored. Also indentation was incorrectly rendered when toJSON returned a primitive instead of an object. This PR fixes that.

Fix JSON.stringify of objects with function values and fix incorrect toJSON indentaion

---

llrt_core/src/json/stringify.rs
tests/unit/json.test.ts

support stringify BigInt
```
JSON.stringify({
v: 1n,
})
// TypeError: Do not know how to serialize a BigInt
```

support stringify BigInt

---

.github/workflows/build.yml
.github/workflows/release.yml
Makefile
README.md

Closed #590
- Multi-flavor support for local machine binaries (linux/macos/windows).
- In the makefile, the method of specifying ARCH for Windows was different from other operating systems, so this has been corrected. However, we have not been able to confirm the execution result after the modification on the local machine. Therefore, there might be an error in the build/release process of Github Actions.

feat: multi-flavor support for local machine binaries

---

.prettierignore
llrt_core/build.rs
llrt_core/src/modules/http/fetch.rs
llrt_core/src/vm.rs
llrt_modules/Cargo.toml
llrt_modules/src/modules/child_process.rs
llrt_modules/src/modules/fs/read_dir.rs
llrt_modules/src/modules/path.rs
llrt_modules/src/modules/process.rs
tests/unit/child_process.test.ts
tests/unit/compile.test.ts
tests/unit/events.test.ts
tests/unit/fetch.test.ts
tests/unit/fs.test.ts
tests/unit/http.test.ts
tests/unit/import.test.ts
tests/unit/json.test.ts
tests/unit/path.unix.test.ts
tests/unit/path.win.test.ts
tests/unit/perf_hooks.test.ts
tests/unit/uuid.test.ts

Optimize path handling

---

.cargo/config.toml

Use haswell target-cpu for x86_64-unknown-linux-musl

---

.github/workflows/build-artifacts.yml
.github/workflows/build-modules.yml
.github/workflows/build.yml
.github/workflows/ci.yml
.github/workflows/release.yml
Makefile
llrt_core/build.rs
llrt_modules/src/modules/child_process.rs
llrt_modules/src/modules/path.rs
tests/unit/json.test.ts

For the convenience of testing, upload the artifacts

ci: upload artifacts

---

Cargo.lock
llrt/Cargo.toml
llrt_core/Cargo.toml
llrt_modules/Cargo.toml

Add bindgen feature for edge devices without buildin bindgen file

add bindgen feature

---

llrt/src/main.rs
llrt_core/src/vm.rs

Add global parameter to execute old js code
```js
a=1
console.log(a)
```

Add global parameter to execute old js code

---

llrt_core/src/modules/console.rs
tests/unit/console.test.ts

close: https://github.com/awslabs/llrt/issues/605
console.log supports multi-byte characters

console.log supports multi-byte characters

---

llrt_core/src/vm.rs

Nested require imports could result in corrupt exports as they shared `module.exports` object.
In this new implementation, each require saves the current `module.export` object in stack memory and create a new one added to global scope. After module is imported the current one is restored. This prevents CJS imports/requires from corrupting the same object and is a much simpler, cleaner and more stable implemenaation.

Fix and simplify CJS imports/requires

---

README.md

The footnotes are displayed in a single line, which is hard to
read. This commit adds a line break to improve readability.

docs(README.md): Improve readability

---

Makefile
llrt_core/src/custom_resolver.rs

- Suppress unnecessary merging of absolute paths (works fine as is, but the path representation is weird when outputting stack traces).
- We also noticed regression in makefile, so we fixed it as well.

fix: Prevent unnecessary merging of absolute paths

---

llrt_core/src/vm.rs

Removed an extra unwrap which causes a called unwrap on None error. Before:
```sh
./target/release/llrt -e "console.log(global)"
```
Fails with:
```
thread 'main' panicked at llrt_core/src/vm.rs:465:83:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

fix: Remove extra unwrap

---

fixtures/export-function.cjs
llrt_core/src/vm.rs
tests/unit/require.test.ts

Fixes https://github.com/awslabs/llrt/issues/608
Fix issue where exported functions where incorrectly treated as objects

Fix CJS function export

---

llrt_core/src/vm.rs
tests/unit/require.test.ts

Fixes https://github.com/awslabs/llrt/issues/610
`require(...)` imports should be cached and return same value for consecutive imports.

fix: multiple CJS requires

---

llrt_core/src/custom_resolver.rs

- In some rare cases, the extension is not specified in the package.json definition of a Node.js package. When loading such packages, an error occurs that cannot be resolved at this time.
- The fix is to complete the “.js”, “.mjs”, and “.cjs” extensions in order if they do not exist at the end, and pass those that do to the loader so they can be loaded.
node_modules/form-data/package.json:
```json
{
"main": "./lib/form_data",
}
```

fix: Correction of extensions when loading Node.js packages

---

llrt_core/src/custom_resolver.rs

- Node.js packages usually use the Node.js API, but some have a module for the Browser.
- In the case of LLRT, as can be seen from the fact that the bundle target of `@aws-sdk` is Browser, if there is a module for Browser, it is more likely to work if you give priority to that one. At least modules like `axios` will now work.
- There may be other ways to specify a different Browser, but there doesn't seem to be a clear rule, so we will address them as soon as we find them.
node_modules/axios/package.json:
```json
"exports": {
".": {
"browser": {
"require": "./dist/browser/axios.cjs",
"default": "./index.js"
},
"default": {
"require": "./dist/node/axios.cjs",
"default": "./index.js"
}
},
},
```
_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …

feat: Browser priority for loading Node.js packages

---

llrt_modules/src/modules/events/event.rs
llrt_modules/src/modules/events/mod.rs
tests/unit/events.test.ts

- Initial implementation of `Event` to advance WinterCG compliance.
https://dom.spec.whatwg.org/#event
- Since we do not know how much is really needed on the server side, we will start with the minimum necessary implementation. However, packages such as `tinybench` work well with this implementation.
```javascript
// bench.js
// import { Event } from "event-target-shim";
// globalThis.Event = Event
import { Bench } from 'tinybench';
import mod from './package.json';
const bench = new Bench({ time: 100 });
bench
.add('json', async () => {
JSON.stringify(mod)
})
await bench.warmup();
await bench.run();
console.log(bench.table());
```
```
$ llrt bench.js 
[ {
Task Name: 'json',
ops/sec: '205713',
Average Time (ns): 4861.136447598518,
Margin: '±0.41%',
Samples: 20572
} ]
```
_By submitting …

feat: Initial implementation of Event

---

llrt_core/src/custom_resolver.rs

- This PR is further browser-preferred support for Node.js package loading.
- This support allows packages such as `debug` to be loaded with Browser priority.
node_modules/debug/package.json:
```json
{
"browser": "./src/browser.js",
}
```

feat: More browser priority support when loading Node.js packages

---

API.md
modules/llrt_os/src/lib.rs
types/os.d.ts

- This is an implementation of `os.arch()` used by `@opensearch-project/opensearch` and others.

feat: Implementation of os.arch()

---

API.md
modules/llrt_buffer/src/buffer.rs
types/buffer.d.ts

This is an implementation of `buffer.constants` used by `@opensearch-project/opensearch` and others.
- `constants.MAX_LENGTH` :  Conforms to the Node.js specification.
https://nodejs.org/api/buffer.html#bufferconstantsmax_length
- `constants.MAX_STRING_LENGTH` :  Since we did not know what to define, we chose a minimum value for the major runtimes. If you have a more suitable value, I would appreciate your advice.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/length#description

feat: Implementation of buffer.constants

---

.github/workflows/build-modules.yml
.github/workflows/build.yml
.github/workflows/ci.yml
.github/workflows/publish.yml
.gitmodules
README.md

- Submodules get pulled in automatically by cargo when using a git dependency, this is annoying since we don't need zstd most of the time. This adds update=none to it so it won't do that, but the downside is that we need to override it elsewhere.

Submodule update=none

---

llrt_core/src/runtime_client.rs
modules/llrt_http/src/fetch.rs
modules/llrt_http/src/lib.rs

Allow consumers to supply their own `hyper` client when intializing `fetch`.
Combined with https://github.com/awslabs/llrt/pull/655 this will allow people to add `fetch` with their own configured hyper clients. This is particularly important for FIPS compliance.

feat: allow `fetch` to be initialized with user-provided client

---

llrt_core/src/module_loader/loader.rs
llrt_core/src/vm.rs

Fixes https://github.com/awslabs/llrt/issues/662
First loaded file should be an import. Exports are still available through global scope but does nothing fir the root file.

Fix top level await for initial file

---

modules/llrt_process/src/lib.rs

- Some Node.js packages use `process.versions.node` as a decision condition.
For example : https://www.npmjs.com/package/cls-hooked?activeTab=readme
- Having a provisional version in `process.versions.node` takes compatibility a little further.
- `22.11.0` is the latest LTS version of Node.js at the time of implementation. If there are no inconveniences, there is no need to change it in the future.

feat: Implementation of process.versions.node

---

llrt_core/src/module_loader/resolver.rs

Fixed #671
- Fix package.json so that “index” is used as the name of the file directly under it when the resolved result is a directory.

fix: Improved package.json resolution logic

---

llrt/src/main.rs
llrt_core/src/module_loader/loader.rs
llrt_core/src/module_loader/mod.rs
llrt_core/src/module_loader/resolver.rs
llrt_core/src/modules/js/@llrt/test/SocketClient.ts
llrt_core/src/vm.rs
modules/llrt_path/src/lib.rs
tests/unit/require.test.ts

CJS imports via ESM now returns the default export if present. This should help with https://github.com/awslabs/llrt/pull/668 and maintain better consistency with Node.
@nabetti1720 even tho all testes are passing, can you verify this doesn't change expected CJS import behavior from ESM?

fix: CJS export default

---

llrt_core/src/module_loader/loader.rs
llrt_core/src/module_loader/resolver.rs
llrt_core/src/vm.rs

Fix regession of CJS imports from node_modules where we auto detected CJS module
Don't add CJS import prefix if importing from require when looking up node modules.

Fix CJS name normalize regression

---

API.md
Cargo.lock
README.md
build.mjs
llrt_core/src/module_builder.rs
llrt_core/src/module_loader/loader.rs
llrt_core/src/modules/mod.rs
llrt_core/src/vm.rs
llrt_modules/Cargo.toml
llrt_modules/README.md
llrt_modules/src/lib.rs
modules/llrt_assert/Cargo.toml
modules/llrt_assert/src/lib.rs
tests/unit/assert.test.ts
types/assert.d.ts
types/index.d.ts

#628
The following Node.js APIs, which are also used in the libraries on which `aws-xray-sdk-core` depends, have been implemented. Note that we do not intend to support all APIs from the beginning.
- assert.ok()

feat: Initial implementation of assert module

---

llrt_core/src/module_loader/resolver.rs

Closed #677
This PR addresses basic loading of the imports field in package.json.
import:
```javascript
//  index19.js
import chalk from 'chalk';
console.log(chalk.blue('Hello world!'));
```
```
% llrt index19.js
Hello world!
```
require:
```javascript
//  index19.js
const chalk = require('chalk');
console.log(chalk.blue('Hello world!'));
```
```
% llrt index19.js
Hello world!
```

feat: Support imports field in package.json

---

llrt_core/benches/slash_replacement.rs
llrt_core/src/vm.rs
tests/unit/require.test.ts

Fixes https://github.com/awslabs/llrt/issues/676 & https://github.com/awslabs/llrt/issues/679
Require with default export should only add named exports if not already there.
Also fixes windows paths as cli args.

Fix require builtin path and windows paths

---

.gitignore
fixtures/node_modules/elem-debug/package.json
fixtures/node_modules/elem-debug/src/browser.js
fixtures/node_modules/elem-lodash.merge/index.js
fixtures/node_modules/elem-lodash.merge/package.json
fixtures/node_modules/elem-uuid/dist/commonjs-browser/index.js
fixtures/node_modules/elem-uuid/package.json
fixtures/test_modules/test-debug.js
fixtures/test_modules/test-lodash.merge.js
fixtures/test_modules/test-uuid.js
llrt_core/src/module_loader/resolver.rs
tests/unit/require.test.ts

Fixed #667
Related #641 
Fixed an issue where the error `SyntaxError: Could not find export 'default' from '...'` occurred when loading a CJS module from an import statement.
- When resolving a Node.js Package, we now also determine whether the package is CJS.
- After that, if we determine that it is a CJS module called by import statement, we now use prefix `__cjsm:` to achieve this behavior.
The following use case, which was an issue in #641, will now work:
```javascript
// powertoolsLogger.js
import { Logger } from '@aws-lambda-powertools/logger'
const logger = new Logger()
logger.info('Hello world')
```
```
% llrt powertoolsLogger.js 
{"level":"INFO","message":"Hello world","sampling_rate":0,"service":"service_undefined","timestamp":"2024-11-17T01:52:13.459Z"}
```
_By submitting this …

fix: Improved behavior when loading CJS modules from import statements

---

README.md
llrt_core/src/environment.rs
llrt_core/src/module_loader/loader.rs
llrt_core/src/module_loader/mod.rs
llrt_core/src/module_loader/resolver.rs

https://github.com/awslabs/llrt/pull/680#issuecomment-2482365305
This PR adds the ability to toggle platform preferences in the Node.js package resolver.
```javascript
// index19.js
import chalk from 'chalk';
console.log(chalk.blue('Hello world!'));
```
Use "browser":
```
% export LLRT_PLATFORM=browser
% llrt index19.js
Hello world!
```
Use "node":
```
% export LLRT_PLATFORM=node
% llrt index19.js
ReferenceError: Error resolving module 'node:tty' from '/Users/shinya/Workspaces/llrt-test/node_modules/chalk/./source/vendor/supports-color/index.js'
```
NOTE: This behavior is currently as expected, as the tty module has not yet been merged into mainline.
Non use:
```
% unset LLRT_PLATFORM
% llrt index19.js
Hello world!
```
_By submitting this pull request, I confirm that you can use, modify, …

feat: Resolver control by environment variable "LLRT_PLATFORM"

---

sdk.cfg

Fixed #694
This PR fixes the issue by removing endpoint `sync-states` from the definition file that are defined in the `@aws-sdk/client-sfn` document but not implemented in the actual source, preventing timeouts during pre-connection at LLRT startup.

fix: Removed invalid endpoints for `@aws-sdk/client-sfn`

---

Cargo.lock
libs/llrt_utils/Cargo.toml
libs/llrt_utils/src/class.rs
libs/llrt_utils/src/lib.rs
libs/llrt_utils/src/object.rs
libs/llrt_utils/src/primordials.rs
llrt_core/src/modules/console.rs
llrt_core/src/vm.rs
modules/llrt_buffer/src/buffer.rs
modules/llrt_exceptions/Cargo.toml
modules/llrt_exceptions/src/lib.rs
modules/llrt_url/src/url_search_params.rs

BasePrimordials & BufferPrimordials provide cached fields for common objects for faster lookup

Add primordials for faster common object lookup

---

Cargo.lock
Cargo.toml
build.mjs
llrt_core/src/module_builder.rs
llrt_core/src/modules/mod.rs
llrt_modules/Cargo.toml
llrt_modules/src/lib.rs
modules/llrt_tty/Cargo.toml
modules/llrt_tty/src/lib.rs
types/index.d.ts
types/tty.d.ts

Add tty module and use libc to implement tty.isatty function

modules: add tty

---

libs/llrt_numbers/src/lib.rs

https://github.com/awslabs/llrt/issues/712
In Node, `(0).toString(16)` returns `"0"`, whereas in LLRT it returns `""`. This PR updates the `internal_i64_to_base_n` function so that the LLRT implementation is consistent with the Node.

Fix `toString()` of 0 for all radix values

---

libs/llrt_utils/Cargo.toml
libs/llrt_utils/src/mc_oneshot.rs

Store waiters in Vec instead of busy waiting

Store wakers in Vec instead of busy waiting

---

Cargo.lock
fixtures/require.mjs
llrt_core/Cargo.toml
llrt_core/build.rs
tests/unit/fetch.test.ts
tests/unit/require.test.ts

Promise poll can likely be removed due to refactored timer/require implementation

Test removing poll patch due to timer/require refactor

---

libs/llrt_json/src/lib.rs
libs/llrt_json/src/parse.rs
llrt_core/src/modules/console.rs
llrt_core/src/vm.rs

Fixes https://github.com/awslabs/llrt/issues/724
Fix log filtering issue and add better json parse error message

Fix console log level filtering and

---

llrt_core/src/modules/console.rs
tests/unit/console.test.ts

Add better console logging for Promises.
Console now logs the state of the promise.

Improved logging of promises

---

modules/llrt_http/src/request.rs
tests/unit/http.test.ts

https://github.com/awslabs/llrt/issues/744
Passing null or undefined into the http Request constructor results in a TypeError. This is a change in behaviour versus nodejs where null or undefined request options are ignored. This PR addresses the problem by first checking the request options argument is an object before setting it on the class.
- [Y] Created unit tests in `tests/unit` and/or in Rust for my feature if needed
- [Y] Ran `make fix` to format JS and apply Clippy auto fixes
- [Y] Made sure my code didn't add any additional warnings: `make check`
- [NA] Added relevant type info in `types/` directory
- [NA] Updated documentation if needed ([API.md](API.md)/[README.md](README.md)/Other)
_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …

Fix a bug where request options set as undefined or null result in a quickjs cast error

---

Cargo.lock
modules/llrt_os/Cargo.toml
modules/llrt_os/src/lib.rs
modules/llrt_os/src/statistics.rs

The sysinfo crate has been updated. This has resulted in some incompatible changes being addressed.

chore(deps): bump sysinfo from 0.32.1 to 0.33.0

---

modules/llrt_buffer/src/buffer.rs
tests/unit/buffer.test.ts

No issue associated with this change.
This PR adds support for `Buffer.isBuffer` and `Buffer.isEncoding` (see https://nodejs.org/api/buffer.html).
- [Y] Created unit tests in `tests/unit` and/or in Rust for my feature if needed
- [Y] Ran `make fix` to format JS and apply Clippy auto fixes
- [Y] Made sure my code didn't add any additional warnings: `make check`
- [NA] Added relevant type info in `types/` directory
- [NA] Updated documentation if needed ([API.md](API.md)/[README.md](README.md)/Other)

feat: adding support for Buffer.isBuffer and Buffer.isEncoding

---

modules/llrt_crypto/src/subtle/decrypt.rs
modules/llrt_crypto/src/subtle/encrypt.rs
modules/llrt_crypto/src/subtle/mod.rs

We created the following enum types and moved more of the implementation into them:
- AesCbcEncVariant
- AesCbcDecVariant
- AesCtrVariant

refactor(crypto): implement of AesCbc*Variant and AesCtrVariant

---

API.md
modules/llrt_crypto/src/subtle/key_algorithm.rs

- Fixed a bug in generateKey where the usage judgment for RSA-OAEP and RSA-PSS was reversed.
- In addition, the order of conditional judgments has been fine-tuned.

fix(crypto): fix a usage error in RSA-OAEP

---

example/functions/src/ssr.ts

Closes #769
async hooks won't be supported and are discouraged, the edge version of React DOM doesn't use async hooks.

fix: update React DOM to use edge

---

llrt_core/src/module_loader/resolver.rs
modules/llrt_child_process/src/lib.rs
modules/llrt_net/src/lib.rs

After applying the latest rust toolchain, we found new incompatibilities and have fixed them.
```
% rustup update          
info: syncing channel updates for 'stable-aarch64-apple-darwin'
info: syncing channel updates for 'nightly-aarch64-apple-darwin'
info: checking for self-update
stable-aarch64-apple-darwin unchanged - rustc 1.84.0 (9fc6b4312 2025-01-07)
nightly-aarch64-apple-darwin unchanged - rustc 1.86.0-nightly (824759493 2025-01-09)
```

fix(core): fix incompatibilities caused by the latest cargo fix

---

fixtures/node_modules/elem-react-dom/cjs/react-dom-server.edge.development.js
fixtures/node_modules/elem-react-dom/cjs/react-dom.development.js
fixtures/node_modules/elem-react-dom/index.js
fixtures/node_modules/elem-react-dom/package.json
fixtures/node_modules/elem-react-dom/server.edge.js
fixtures/test_modules/test-react-dom.js
llrt_core/src/module_loader/resolver.rs
tests/unit/require.test.ts

For example, when `react-dom/server.edge` was called, this issue occurred because `react-dom` was required again inside the package.
```javascript
import * as dom from "react-dom/server.edge";
console.log(dom);
```
```
Error: IO Error: No such file or directory (os error 2)
at <anonymous> (__cjs:/Users/shinya/Workspaces/llrt-test/node_modules/react-dom/cjs/react-dom-server.edge.development.js:7330:18)
at <anonymous> (__cjs:/Users/shinya/Workspaces/llrt-test/node_modules/react-dom/cjs/react-dom-server.edge.development.js:8975:3)
at <anonymous> (__cjs:/Users/shinya/Workspaces/llrt-test/node_modules/react-dom/server.edge.js:9:7)
% bun reproduction.js
Module {
default: {
version: "19.0.0",
renderToReadableStream: [Function],
renderToString: …
```

fix(core): fix a bug where a package's code could not load its own package

---

README.md

I would argue that this improvement is necessary because systemd isn't enabled by default and so currently, users have to look up what to do about the error `error: cannot communicate with server: Post "http://localhost/v2/snaps/zig": dial unix /run/snapd.socket: connect: no such file or directory`.

docs: add note about systemd to wsl build instructions

---

modules/llrt_fs/src/read_dir.rs
modules/llrt_path/src/lib.rs
tests/unit/fs.test.ts

Fixes https://github.com/awslabs/llrt/issues/786
Pops last char if ending with separator.

Fix readdir ending with slash

---

fixtures/node_modules/elem-aws-lambda-powertools/commons/lib/cjs/index.js
fixtures/node_modules/elem-aws-lambda-powertools/commons/lib/cjs/typeUtils.js
fixtures/node_modules/elem-aws-lambda-powertools/commons/lib/esm/index.js
fixtures/node_modules/elem-aws-lambda-powertools/commons/lib/esm/typeUtils.js
fixtures/node_modules/elem-aws-lambda-powertools/commons/package.json
fixtures/node_modules/elem-aws-lambda-powertools/jmespath/lib/cjs/index.js
fixtures/node_modules/elem-aws-lambda-powertools/jmespath/lib/esm/index.js
fixtures/node_modules/elem-aws-lambda-powertools/jmespath/package.json
fixtures/test_modules/test-aws-lambda-powertools-jmespath.js
llrt_core/src/module_loader/resolver.rs
tests/unit/require.test.ts

Fixes #766 
This PR fixes an issue where scope/name format names (including internal use) that contained multiple "/" could not be loaded correctly.
Case1: 
```
% cat reproduction.js 
const a = require('@aws-lambda-powertools/idempotency');
console.log(a);
{
__esModule: true,
IdempotencyItemAlreadyExistsError: [class: IdempotencyItemAlreadyExistsError],
IdempotencyItemNotFoundError: [class: IdempotencyItemNotFoundError],
IdempotencyAlreadyInProgressError: [class: IdempotencyAlreadyInProgressError],
IdempotencyInvalidStatusError: [class: IdempotencyInvalidStatusError],
IdempotencyValidationError: [class: IdempotencyValidationError],
IdempotencyInconsistentStateError: [class: IdempotencyInconsistentStateError],
IdempotencyPersistenceLayerError: [class: …
```

fix(core): load packages expressed through multiple "/"

---

Cargo.lock
llrt_core/src/http.rs
llrt_core/src/vm.rs
modules/llrt_http/Cargo.toml
modules/llrt_http/src/cached_dns_resolver.rs
modules/llrt_http/src/fetch.rs
modules/llrt_http/src/incoming.rs
modules/llrt_http/src/lib.rs
modules/llrt_http/src/response.rs
shims/sdk-stream-mixin.js

Limit parallel fetches to 500 to reduce contention on network stack. This significantly improves performance when a lot of requests are executed in parallel. 
This PR also contains a DNS cache implemementation that caches DNS lookups for 300 seconds. DNS parallel lookups are also limited to 5 per host to limit excessive thread spawning.
`Response` also now also only allows for a body to be read once.
```javascript
const res = await fetch("https:///www.amazon.com");
await res.text() //OK
await res.text() //Error
```

(perf): Fetch improvements

---

.github/workflows/build.yml
.github/workflows/ci.yml
.github/workflows/release.yml
Cargo.lock

Use ARM runner

---

libs/llrt_json/src/parse.rs
libs/llrt_utils/src/bytes.rs
llrt_core/src/modules/llrt/hex.rs
llrt_core/src/modules/llrt/uuid.rs
llrt_core/src/modules/llrt/xml.rs
llrt_core/src/modules/util/text_decoder.rs
modules/llrt_buffer/src/buffer.rs
modules/llrt_crypto/src/crc32.rs
modules/llrt_crypto/src/lib.rs
modules/llrt_crypto/src/md5_hash.rs
modules/llrt_crypto/src/sha_hash.rs
modules/llrt_crypto/src/subtle/digest.rs
modules/llrt_crypto/src/subtle/encryption.rs
modules/llrt_crypto/src/subtle/encryption_algorithm.rs
modules/llrt_crypto/src/subtle/key_algorithm.rs
modules/llrt_crypto/src/subtle/sign.rs
modules/llrt_crypto/src/subtle/verify.rs
modules/llrt_fs/src/write_file.rs
modules/llrt_http/src/body.rs
modules/llrt_http/src/fetch.rs
modules/llrt_http/src/request.rs
modules/llrt_http/src/response.rs
modules/llrt_stream/src/writable.rs
modules/llrt_zlib/src/lib.rs

Closed #700
This PR removes the `expect` instruction used in ObjectBytes's `as_bytes()` and allows it to return `std::result::Result` or `rquickjs::Result` types.

fix(utils): remove expect from ObjectBytes

---

Cargo.lock
llrt_core/src/http.rs
llrt_core/src/vm.rs
modules/llrt_http/Cargo.toml
modules/llrt_http/src/cached_dns_resolver.rs
modules/llrt_http/src/fetch.rs
modules/llrt_http/src/incoming.rs
modules/llrt_http/src/lib.rs
modules/llrt_http/src/response.rs
shims/sdk-stream-mixin.js

Limit parallel fetches to 500 to reduce contention on network stack. This significantly improves performance when a lot of requests are executed in parallel. 
This PR also contains a DNS cache implemementation that caches DNS lookups for 300 seconds. DNS parallel lookups are also limited to 5 per host to limit excessive thread spawning.
`Response` also now also only allows for a body to be read once.
```javascript
const res = await fetch("https:///www.amazon.com");
await res.text() //OK
await res.text() //Error
```

(perf): Fetch improvements v2

---

shims/@aws-crypto/crc32.js
shims/@aws-crypto/crc32c.js

fixed #821 
In the current build script, when `@aws-crypto/util` is called from shims file, it seems that the file is not generated with the correct chunk file name.
This may need to be improved in the future.
However, this time, the implementation being called is not that large, so I decided to hard-code it.

fix(shims): fix @aws-crypto shims not loading

---

llrt/src/repl.rs

On Windows, each key event has two kinds, press and release, so duplicate output may occur.
On Unix platforms there is only a press event
close https://github.com/awslabs/llrt/issues/826

repl: skip release KeyEventKind on windows

---

API.md
modules/llrt_fs/src/chmod.rs
modules/llrt_fs/src/lib.rs
modules/llrt_fs/src/mkdir.rs
types/fs.d.ts
types/fs/promises.d.ts

close: https://github.com/awslabs/llrt/issues/828

fs: add chmodSync

---

llrt_core/build.rs

fix #846 
There was an error in the index generation process for the bytecode cache.
Specifically, the index was generated in a format different from the chunk file name written in the code (specifically, the extension was missing), which caused a resolution error.

fix(core): fix bytecode cache index generation error

---

llrt_core/src/modules/js/@llrt/test/index.ts
tests/unit/dns.test.ts

Test introduced by https://github.com/awslabs/llrt/pull/825 had assertions in callbacks of non-asynchronous functions. This will (by design) crash the process if not handled correctly.
Throwing an error in a callback will result in process exit. This PR fixes the assertions by wrapping the lookup in a promise. Another option would be to use the `done` callback and an inner try catch in the callback.

fix: dns test

---

llrt_core/src/module_loader/resolver.rs

Fixed #875 
Fixed an issue where paths could not be resolved correctly in require/import when the base path contained a symbolic link.
```
% pwd
/Users/shinya/Workspaces/llrt-test/symlink
% ls -lFa .    
total 16
drwxr-xr-x   5 shinya  staff   160  3  8 22:36 ./
drwxr-xr-x  90 shinya  staff  2880  3  8 12:27 ../
-rw-r--r--   1 shinya  staff    72  3  8 12:28 bar.js
drwxr-xr-x   7 shinya  staff   224  3  8 22:37 bin/
-rw-r--r--   1 shinya  staff    42  3  8 22:29 foo.js
% ls -lFa bin
total 16
drwxr-xr-x  7 shinya  staff  224  3  8 22:37 ./
drwxr-xr-x  5 shinya  staff  160  3  8 22:36 ../
lrwxr-xr-x  1 shinya  staff   54  3  8 22:37 absolute@ -> /Users/shinya/Workspaces/llrt-test/symlink/bin/hoge.js
lrwxr-xr-x  1 shinya  staff    9  3  8 12:29 foo@ -> ../foo.js
-rw-r--r--  1 shinya  staff …
```

fix(core): resolve symbolic links

---

API.md
modules/llrt_buffer/src/buffer.rs
tests/unit/buffer.test.ts
types/buffer.d.ts

This PR implements some methods that I need for my project.
- [Static method: Buffer.allocUnsafe(size)](https://nodejs.org/api/buffer.html#static-method-bufferallocunsafesize)
- [Static method: Buffer.allocUnsafeSlow(size)](https://nodejs.org/api/buffer.html#static-method-bufferallocunsafeslowsize)
- [buf.copy(target[, targetStart[, sourceStart[, sourceEnd]]])](https://nodejs.org/api/buffer.html#bufcopytarget-targetstart-sourcestart-sourceend)
- [buf.write(string[, offset[, length]][, encoding])](https://nodejs.org/api/buffer.html#bufwritestring-offset-length-encoding)
- [buf.writeInt32BE(value[, offset])](https://nodejs.org/api/buffer.html#bufwriteint32bevalue-offset)
By generalizing `buf.writeInt32BE()`, we also support:
- [buf.writeBigInt64BE(value[, …

feat(buffer): implement some static and prototype methods

---

libs/llrt_json/src/stringify.rs
libs/llrt_logging/src/lib.rs

In console refactor we introduced a lot of bitwise premature optimizations to reduce branches. Compiler does a much better job of optimizing since we can use chars instead of slices etc. Code is also way more maintainable/readable now.

chore: Remove bitwise BS

---

fixtures/test903/bar.mjs
fixtures/test903/foo.mjs
llrt_core/src/module_loader/resolver.rs
tests/unit/require.test.ts

Fixed #903
Fixed an issue where path::normalize() was incorrectly removing relative paths when the path started with "../", resulting in a different file path when combined with the base directory.

fix(core): fix for relative paths being accidentally stripped

---

llrt_core/src/module_loader/resolver.rs
tests/unit/require.test.ts

Closed #904
Supports loading assets defined in file URL format.

feat(core): Support load module from file URL

---

libs/llrt_logging/src/lib.rs
modules/llrt_buffer/src/buffer.rs
modules/llrt_crypto/src/subtle/derive.rs
modules/llrt_crypto/src/subtle/export_key.rs
tests/unit/console.test.ts

Fixes https://github.com/awslabs/llrt/issues/911
Fixes broken surrogate pairs. Thanks for reporting @ahaoboy 

fix: Print utf8 replacement char for broken surrogate pairs

---

.cargo/config.toml
modules/llrt_stream_web/src/readable/byob_reader.rs
modules/llrt_stream_web/src/readable/byte_controller.rs
modules/llrt_stream_web/src/readable/stream/mod.rs
modules/llrt_stream_web/src/utils/promise.rs
modules/llrt_stream_web/src/writable/default_writer.rs
modules/llrt_stream_web/src/writable/stream/mod.rs

Fixes https://github.com/awslabs/llrt/issues/926
Some Stream classes did not correctly trace QJS objets leading to leaks on runtime exit. Leaks on runtime exit causes an assertion failure leading to a crash (by design). This PR adds missing traces, fixing the leaks

fix: Readable stream leaks

---

llrt_core/src/modules/module.rs

fixed #886 
By immediately dropping the `state` obtained with `borrow_mut()` when it is no longer needed, we can avoid crashes caused by multiple `borrow_mut()` calls.
At least it won't crash and the search for the module will continue, like so:
```
% cat reproduction.js 
const a = require('pg');
console.log(a);
% llrt reproduction.js
ReferenceError: Error resolving module 'module_root/build/addon.node' from '/Users/shinya/Workspaces/llrt-test/node_modules/bindings/bindings.js'
at bindings (__cjs:/Users/shinya/Workspaces/llrt-test/node_modules/bindings/./bindings.js:112:60)
at <anonymous> (__cjs:/Users/shinya/Workspaces/llrt-test/node_modules/libpq/index.js:1:27)
at <anonymous> (__cjs:/Users/shinya/Workspaces/llrt-test/node_modules/pg-native/index.js:1:12)
at <anonymous> …
```

fix(require): crash when accessing RequireState

---

llrt_core/src/modules/mod.rs
llrt_core/src/modules/module.rs
llrt_core/src/modules/require/mod.rs
llrt_core/src/vm.rs
llrt_modules/README.md
llrt_modules/src/lib.rs
llrt_modules/src/module_builder.rs

We've refactored `require` and `module` to be more independent.
- Previously, the module list output by `ModuleBuilder` was passed directly to `Module::init()`, but now it is passed via global (although I'm not sure if this is a good way to do it).
- This allowed `Module::init()` to have the same specifications as other `init()`, so the attachment method could also be made consistent.
- The `module` contained the implementation of `require`, but we were able to separate the implementation part.
This makes it more likely that we can move `module` to the module directory and `require` to the libs directory. However, in order to make it an independent crate, there are some things to consider about the implementation of `require` (what to do with LLRT and Lambda-specific logic), so we will …

refactor(require/module): further separation of require and module

---

llrt_core/src/compiler.rs
llrt_core/src/modules/embedded/loader.rs
llrt_core/src/modules/embedded/mod.rs
llrt_core/src/modules/embedded/resolver.rs
llrt_core/src/modules/mod.rs
llrt_core/src/modules/require/loader.rs
llrt_core/src/modules/require/mod.rs
llrt_core/src/modules/require/resolver.rs
llrt_core/src/vm.rs

Related #936 
> NOTE: We already have an idea for this issue. It's to split `CustomResolver/Loader` into `NpmJsResolver/Loader` and `EmbeddedResolver/Loader`. `NpmJsResolver/Loader` will be exposed, but `EmbeddedResolver/Loader` will continue to be under the management of core.
> 
> However, some integration will be required in `require`. But it seems that we can deal with it by accepting one user-defined function in `require_resolver()` and making ByteCodeCache judgment.
As mentioned in #936, we have extracted the LLRT-specific bytecode from the previous require. In the future, we plan to expose the require directory as llrt_require, and leave the embedded directory under the management of llrt_core.
However, there are still some tangled parts (src/bytecode.rs, src/modules/utils/*) and …

refactor(require): further separation of npm-require and bytecode-require

---

llrt/src/main.rs
llrt_core/src/modules/js/@llrt/test/index.ts
modules/llrt_process/src/lib.rs
tests/unit/child_process.test.ts
types/process.d.ts

Allows users to set exit code for process.
`process.exitCode = 42`. Also make sure `process.exit()` can be called without args.

feat: process.exitCode

---

Cargo.toml
modules/llrt_timers/src/lib.rs

Fixes: https://github.com/awslabs/llrt/issues/965
Timers are batched for performance reasons. A timer batch was not sorted. This PR sorts timers according to their deadline.

fix: Timer execution order

---

Cargo.lock
modules/llrt_crypto/src/lib.rs
modules/llrt_crypto/src/subtle/crypto_key.rs
modules/llrt_crypto/src/subtle/mod.rs
modules/llrt_exceptions/src/lib.rs
modules/llrt_http/src/request.rs
modules/llrt_http/src/response.rs

Partially fixes
https://github.com/awslabs/llrt/issues/967
Fixes:
https://github.com/awslabs/llrt/issues/970
Exposes the Crypto, SubtleCrypto and CryptoKey constructors to `globalThis`.
Additionally this PR adds some `toStringTag` symbol getters for Web APIs

Increased Web Platform compatibility

---

modules/llrt_timers/src/lib.rs
tests/unit/asynchronous-processing-discipline.test.ts

This code verifies that all microtasks have been processed before processing a macrotask. If it works correctly, the output will start in alphabetical order.
<details>
<summary> realitySettimeout-nested.js</summary>
```javascript
// realitySettimeout-nested.js
console.log("[A] 🦖 MAINLINE: Start");
setTimeout(() => {
console.log("[D] ⏰ TIMERS: setTimeout[0ms]");
Promise.resolve("1st Promise")
.then((value) => console.log("[E] 👦 MICRO: Resolved value:", value))
.then(() => console.log("[F] 👦 MICRO: Next chain"));
setTimeout(() => {
console.log("[J] ⏰ TIMERS: setTimeout[0ms]");
Promise.resolve("2nd Promise")
.then((value) => console.log("[K] 👦 MICRO: Resolved value:", value))
.then(() => console.log("[L] 👦 MICRO: Next chain"));
});
});
setTimeout(() => {
console.log("[G] ⏰ TIMERS: …
```

fix(timers): not completing all microtasks before completing a macrotask

---

llrt_core/src/modules/llrt/uuid.rs
modules/llrt_os/src/network.rs
modules/llrt_os/src/statistics.rs
modules/llrt_process/src/lib.rs

Fixes warnings that occur when updating the Rust toolchain.

fix: WARNING: lifetime flowing from input to output with different syntax can be confusing

---

Cargo.lock
llrt_core/Cargo.toml
modules/llrt_url/Cargo.toml
wpt_errors.txt

Related: #487
Related: https://github.com/servo/rust-url/issues/952
- The reported issues have been resolved in url 2.5.3, so we will be moving forward with the dependency. We compared the binary size and there was no change in KB.
No change in results before and after:
```sh
% du -k ./target/aarch64-apple-darwin/release/llrt
10588   ./target/aarch64-apple-darwin/release/llrt
```
- This update also improves WPT compatibility.

chore(url): update dependencies

---

libs/llrt_numbers/src/lib.rs
tests/unit/numbers.test.ts

Fixed: #1011 
Fixed an issue where numbers larger than 32-bits could not be converted in `Number.toString(radix)`.
```javascript
const d = Date.now().toString(16);
console.log(d)
console.log(d.length)
console.log(d[11] == String.fromCharCode(0))
console.log(d[11] == undefined)
console.log(Buffer.from(d));
```
llrt: 
```
19759a74897
11
false
true
Buffer [ 49, 57, 55, 53, 57, 97, 55, 52, 56, 57, 55 ]
```
node.js:
```
% node reproduction.js 
19759a7571b
11
false
true
<Buffer 31 39 37 35 39 61 37 35 37 31 62>
```

fix(number): fix Number.toString(radix)

---

modules/llrt_fetch/src/headers.rs
wpt_errors.txt

Although it's still far from perfect, we've improved our compliance with the Fetch standard.

fix(fetch/headers): Improve Headers class conformance to Fetch standards

---

types/process.d.ts

Adds the env property to the process.d.ts type definition.
This allows TypeScript users to access process.env without encountering type errors.

Add process.env types to process.d.ts

---

libs/llrt_logging/src/lib.rs
libs/llrt_numbers/src/lib.rs
tests/unit/numbers.test.ts

Fixes https://github.com/awslabs/llrt/issues/1055
Fixes `.toString()` of `NaN`, `Infinity`, and floats. Before:
```
Welcome to LLRT v0.6.0-beta (darwin, x64)
Type ".exit" or Ctrl+C or Ctrl+D to exit
> NaN.toString()
0
> NaN.toString(2)
0
> NaN.toString(10)
0
> NaN.toString(16)
0
> Infinity.toString()
Infinity
> Infinity.toString(2)
[1]    26123 illegal hardware instruction  ./llrt
> Infinity.toString(10)
[1]    26179 illegal hardware instruction  ./llrt
> Infinity.toString(16)
[1]    26269 illegal hardware instruction  ./llrt
> 123.456.toString()
123
> 123.456.toString(2)
1111011
> 123.456.toString(10)
123
> 123.456.toString(16)
7b
```
After:
```
Welcome to LLRT v0.6.0-beta (darwin, x64)
Type ".exit" or Ctrl+C or Ctrl+D to exit
> NaN.toString()
NaN
> NaN.toString(2)
NaN
> NaN.toString(10) …
```

fix: `.toString()` for `NaN`, `Infinity`, and floats

---

libs/llrt_numbers/src/lib.rs
tests/unit/numbers.test.ts

Fixes https://github.com/awslabs/llrt/issues/1062
Conversion to string did not account for Boxed numbers. Also explicitly passing undefined (or void 0) to toString as argument did not work. This PR addresses those issues

Fix boxed numbers to string

---

Cargo.lock
modules/llrt_fetch/Cargo.toml
modules/llrt_fetch/src/fetch.rs
wpt_errors.txt

- It passes WPT by correctly handling percent encoding in data-urls.

fix(fetch): correctly handle percent encoding in data-urls

---

modules/llrt_fetch/src/body.rs
modules/llrt_fetch/src/lib.rs
modules/llrt_fetch/src/request.rs
modules/llrt_fetch/src/response.rs
wpt_errors.txt

- The BOM must be ignored (do nothing) in `body.text()` and `body.json()`.
- The same is true for `Request` and `Response`, which is the body-mixin.

fix(fetch): remove the BOM from body.text() and body.json()

---

llrt_core/src/modules/js/@llrt/test/worker.ts
tests/unit/jest-expect.test.ts

Closes #1071
This PR passes the current test suite to `runTests`, in order for it to correctly invoke the `beforeEach` and `afterEach` hooks.

fix(test): correctly call beforeEach/afterEach for tests

---

libs/llrt_json/src/stringify.rs
llrt_core/src/modules/require/mod.rs
modules/llrt_async_hooks/src/lib.rs
modules/llrt_dns/src/lib.rs
modules/llrt_timers/src/lib.rs

Fixed #1093
- We can probably get the pointer properly by using qjs's helper functions.
64bit: https://github.com/DelSkayn/rquickjs/blob/50cbbf2b163122c2456ff0ade7a242c068ee136a/sys/src/inlines/ptr_64.rs#L27-L29
```rust
#[inline]
pub unsafe fn JS_VALUE_GET_PTR(v: JSValue) -> *mut c_void {
v.u.ptr
}
```
32bit: https://github.com/DelSkayn/rquickjs/blob/50cbbf2b163122c2456ff0ade7a242c068ee136a/sys/src/inlines/ptr_32_nan_boxing.rs#L17-L19
```rust
#[inline]
pub unsafe fn JS_VALUE_GET_PTR(v: JSValue) -> *mut c_void {
v as isize as *mut c_void
}
```

fix: use qjs helper functions to get the pointer

---

modules/llrt_fetch/src/request.rs
modules/llrt_fetch/src/response.rs
tests/unit/http.test.ts
tests/wpt/fetch/api/resources/utils.js
wpt_errors.txt

- The support for the bodyUsed property of the Request class was insufficient, so it has been improved.
- Ideally, body handling should be standardized according to the Body-Mixin concept, but this will take time, so we will do it another time.

fix(fetch): improved compatibility of bodyUsed property

---

libs/llrt_encoding/src/lib.rs
modules/llrt_util/src/text_decoder.rs
wpt_errors.txt

- Unmatched BOMs are not ignored and are treated as garbage bytes.

fix(encoding): fix trimming even if BOM character code does not match

---

Makefile
modules/llrt_fetch/src/fetch.rs
tests/wpt/README.md
tests/wpt/WebCryptoAPI.derive_bits_keys.test.ts
tests/wpt/fetch.api.basic.test.ts
tests/wpt/fetch.harness.js
wpt_errors.txt

- Although the available environments may be limited, in order to expand the scope of wpt testing, we have made it a prerequisite for running `wpt serve` when running wpt tests.
- Some tests that could not be run because the server was not present can now be run and produce different results. Some tests have insufficient URL support, which seems to have caused a regression, but we will make adjustments in another PR.

feat(wpt): expand the scope of wpt testing

---

API.md
modules/llrt_crypto/src/lib.rs
tests/unit/crypto.test.ts

Related #537
While looking up how to use LLRT in a repository, I came across a statement that the `nanoid` package would not load. 
```javascript
import { nanoid } from "nanoid";
console.log(nanoid());
```
```
% llrt reproduction.js
SyntaxError: Could not find export 'webcrypto' in module 'crypto'
```
As far as the node documentation is concerned, it is equivalent to `globalThis.crypto`, and this has also been confirmed in tests with other runtimes, so LLRT will also expose the same thing as `globalThis.crypto` as `webcrypto`.
```
% llrt reproduction.js
sUR5qTCMiKp8gYRDXjW3o
% bun reproduction.js 
VMPNLBjBGxcqi-FUTh-ER
```

feat(crypto): expose webcrypto in crypto module

---

fixtures/node_modules/elem-hono/dist/cjs/utils/url.js
fixtures/node_modules/elem-hono/dist/index.js
fixtures/node_modules/elem-hono/package.json
fixtures/test_modules/test-elem-hono.js
llrt_core/src/modules/require/resolver.rs
tests/unit/require.test.ts

Fixed: #1129
This PR will allow wildcards in package.json exports to be resolved correctly.
```javascript
import { getQueryParam } from 'hono/utils/url'
console.log(getQueryParam);
```
```
[function: _getQueryParam]
% bun reproduction.js 
[Function: _getQueryParam]
```

fix(require):  correctly handle wildcards in package.json

---

fixtures/cjs-handler.cjs
fixtures/tla-webcall-handler.mjs
llrt_core/src/runtime_client.rs

Fixes https://github.com/awslabs/llrt/issues/1070
Uses regular module import instead of require which from an asynchronous context (Tokio) can advance the runtime.

fix: add CJS and TLA webcall handler fixtures

---

llrt_core/src/modules/embedded/resolver.rs
llrt_core/src/modules/require/mod.rs
llrt_modules/src/module_builder.rs

Fixed #1150 
Related #1111
- Fixed an issue where trailing slashes would not resolve correctly if the module was an internal module and not a package.
```javascript
const a = require('middy/middlewares');
console.log(a);
```
```
{
cache: [function: (anonymous)],
cors: [function: (anonymous)],
doNotWaitForEmptyEventLoop: [function: (anonymous)],
httpContentNegotiation: [function: (anonymous)],
httpErrorHandler: [function: (anonymous)],
httpEventNormalizer: [function: (anonymous)],
httpHeaderNormalizer: [function: (anonymous)],
httpMultipartBodyParser: [function: (anonymous)],
httpPartialResponse: [function: (anonymous)],
httpSecurityHeaders: [function: (anonymous)],
jsonBodyParser: [function: (anonymous)],
s3KeyNormalizer: [function: (anonymous)], …
```

fix(require): support resolving modules when require path ends with a trailing slash

---

README.md
build.mjs
llrt_core/src/modules/js/stream/promises.ts
llrt_modules/README.md

- Currently, LLRT exposes a node-compatible stream-polyfill as embedded code.
- This PR exposes `stream/promises` in the same way as `stream`.
```javascript
import { Readable } from "node:stream"; console.log(Readable);
import { Writable } from "node:stream"; console.log(Writable);
import { Duplex } from "node:stream"; console.log(Duplex);
import { Transform } from "node:stream"; console.log(Transform);
import { PassThrough } from "node:stream"; console.log(PassThrough);
import { finished } from "node:stream"; console.log(finished);
import { pipeline } from "node:stream"; console.log(pipeline);
import { finished as promises_finished } from "node:stream/promises"; console.log(promises_finished);
import { pipeline as promises_pipeline } from "node:stream/promises"; …
```

feat(embedded): expose stream/promises by polyfill
