- README.md
*Issue #, if available:* N/A
*Description of changes:* Node.js does support generating UUIDs without dependencies (with `crypto.randomUUID()`).
> Fix Compatibility matrix

- API.md
- src/encoding/mod.rs
- tests/encoding.test.ts
`atoa` & `btoa` global functions
> atob & btoa global functions

- Cargo.lock
- Cargo.toml
- src/os.rs
Fixes: https://github.com/awslabs/llrt/issues/128
change package to uname rather than uname-rs
> Fix os.release() segfault

- example/functions/src/react/TodoList.tsx
#134
Changed message from 'could not create' to 'could not delete'
> Error message updated to reflect action

- src/os.rs
```js
console.log(os.version())
```
> add os.version

- build.mjs
- src/process.rs
- src/vm.rs
- tests/process.test.ts
closes #161
Hey @richarddavison , please review carefully, I'm not as good in rust as in js and ts.
But I covered implementation with tests and it looks good to me,
if you see any improvements to make, pls let me know.
> Make `process` as module

- src/http/blob.rs
- src/http/body.rs
- src/http/fetch.rs
- src/http/headers.rs
- src/http/mod.rs
- src/http/request.rs
- src/http/response.rs
- src/http/url_search_params.rs
- src/process.rs
- src/utils/object.rs
- tests/http.test.ts
- tests/xml.test.ts
Fixes https://github.com/awslabs/llrt/issues/168
Implements better [WHATWG Fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) compatibility.
Still, readable streams are not yet implemented for fetch.
> Increase fetch compat

- build.mjs
- shims/collect-stream-body.js
- src/crypto/mod.rs
- src/http/blob.rs
- src/http/body.rs
- src/http/request.rs
- src/http/response.rs
- src/http/url.rs
- src/utils/class.rs
- tests/http.test.ts
Increased 1ece463450aaab989a4ecd612caf34606e1c86ef introduced regression while reading response body in some AWS SDK Clients. This PR fixes the regression.
> Fix AWS request/response

- src/http/url.rs
- src/js/@llrt/init.ts
- src/main.rs
- tests/http.test.ts
Fixes: https://github.com/awslabs/llrt/issues/215
Port was missing. Also removed trailing `:` from protocol if present when setting the property
> Fix url port option

- GOVERNANCE.md
- MAINTAINERS.md
Adding Minimum Viable Governance 
> Minimal Governance Model v0

- .github/workflows/build.yml
- .github/workflows/release.yml
- .gitignore
- Cargo.toml
- Makefile
- build.rs
- src/bytecode.rs
- src/bytecode_meta.rs
- src/compiler.rs
- src/compiler_common.rs
- src/main.rs
- src/vm.rs
Create uncompressed versions for OCI (container) usage
> Uncompressed

- src/js/@llrt/init.ts
> Change init endpoint

- build.mjs
Fixes https://github.com/awslabs/llrt/issues/241
Use a simple esbuild plugin to resolve `process` when requiring `process/`
> Resolve builtin process

- example/functions/src/v2.js
- example/infrastructure/src/index.ts
Fixes #238 
* Update the Amazon Linux runtime from version 2 to 2023
* Add a working example to demonstrate how to use a NodeJS runtime and the LLRT layer with `AWS_LAMBDA_EXEC_WRAPPER`
* Updated comments and other copy/paste errors induced by updating the default runtime from Node 18 to 20
* Fix `aws-sdk` external module Node 16 example
> chore: infra example improvements

- src/console.rs
Fixes https://github.com/awslabs/llrt/issues/255
Refactor structured logging support to conform to https://docs.aws.amazon.com/lambda/latest/dg/nodejs-logging.html
> Upgrade structured logging

- API.md
- src/fs/access.rs
- src/fs/mod.rs
- src/fs/read_file.rs
- tests/unit/fs.test.ts
https://github.com/awslabs/llrt/issues/249
Implemented readFileSync
> feat: implement readFileSync

- README.md
In Bundled AWS SDK packages section:
- Add @aws-sdk/s3-request-presigner
- Change sort order (To make it easier to find the desired package)
> Update Bundled AWS SDK packages section in README 

- API.md
- src/fs/access.rs
- src/fs/mod.rs
- src/fs/rm.rs
- tests/unit/fs.test.ts
Implement rmSync, add unit test for rm
> feat: implement rmSync

- Cargo.lock
- Cargo.toml
- linker/cc
- linker/cxx
> Upgrade deps

- src/http/url.rs
- src/http/url_search_params.rs
- tests/unit/http.test.ts
Fixes https://github.com/awslabs/llrt/issues/320
Port should be removed if default for the protocol
> Fix URL port/port when default protocols

- src/http/fetch.rs
- tests/unit/fetch.test.ts
Fixes https://github.com/awslabs/llrt/issues/323
Refactored collection of fetch options and fix bugs
> Fix fetch resource & opts

- API.md
For API.md:
- Minor formatting errors have been corrected.
- The order of links has been rearranged alphabetically.
> docs: fix API.md

- README.md
* Added the `@aws-sdk/client-cognito-identity-provider` to the SDK list in the Readme
> docs: add @aws-sdk/cognito-client-identity-provider SDK to Readme

- src/http/fetch.rs
#340 
- Minimal improvements have been made to allow for redirect processing.[(reference information)](https://fetch.spec.whatwg.org/#http-redirect-fetch)
> feat: Implementation of redirect option for fetch()

- llrt_core/src/modules/http/url_search_params.rs
- tests/unit/http.test.ts
https://github.com/awslabs/llrt/issues/307
Better consistence with web URLSearchParams
> Fix URLSearchParams compliance

- API.md
- Cargo.lock
- llrt_core/Cargo.toml
- llrt_core/src/modules/http/url.rs
- llrt_core/src/modules/http/url_search_params.rs
- llrt_core/src/modules/url.rs
- llrt_core/src/vm.rs
- tests/unit/http.test.ts
https://github.com/awslabs/llrt/issues/305
https://github.com/awslabs/llrt/issues/303
Implement URL utility functions
> Url util functions

- CHANGELOG.md
- Cargo.lock
- llrt/Cargo.toml
- llrt_core/Cargo.toml
- llrt_core/src/environment.rs
- llrt_core/src/modules/net/mod.rs
> Prepare v0.1.13-beta

- CHANGELOG.md
- Cargo.lock
- llrt/Cargo.toml
- llrt_core/Cargo.toml
- tests/unit/events.test.ts
https://github.com/awslabs/llrt/issues/380
Fix `Promise.all` in RIC
- [] Created unit tests in `tests/unit` and/or in Rust for my feature if needed
> Prepare v0.1.14 beta

- API.md
- Cargo.lock
- llrt_core/Cargo.toml
- llrt_core/src/modules/http/blob.rs
- llrt_core/src/modules/http/file.rs
- llrt_core/src/modules/http/mod.rs
- tests/unit/http.test.ts
Refs: #250
https://github.com/awslabs/llrt/issues/250
Implemented the File interface: https://developer.mozilla.org/en-US/docs/Web/API/File. This is a pre-requisite for implementation of FormData.
> File support

- API.md
- llrt_core/src/modules/buffer.rs
- llrt_core/src/modules/crypto/mod.rs
- llrt_core/src/utils/object.rs
- tests/unit/crypto.test.ts
Add the following methods to improve the compliance of `crypto` Object.
- crypto.getRandomValues()
> feat: Improved compliance of crypto object

- Cargo.lock
- llrt_core/Cargo.toml
CRC32c now fixed for nightly compiler
> Update crc32c rep

- API.md
- llrt_core/src/modules/http/url.rs
- tests/unit/http.test.ts
Add the following methods to improve the compliance of `URL` Object.
See also. https://url.spec.whatwg.org/#dom-url-parse
- URL.parse()
> feat: Improved compliance of URL object

- CHANGELOG.md
- Cargo.lock
- llrt/Cargo.toml
- llrt_core/Cargo.toml
> Prepare v0.1.15-beta

- Cargo.lock
- llrt_core/Cargo.toml
- llrt_core/benches/json.rs
- llrt_core/src/json/mod.rs
- llrt_core/src/json/parse.rs
- llrt_core/src/lib.rs
- llrt_core/src/runtime_client.rs
Refactored the JSON parsing logic to utilize recursion rather than a non-recursive tree traversal. This new implementation is more efficient, given that the depth of a JavaScript object is typically not excessively deep, resulting in simpler and more maintainable code.
> Use iterative approach for json parsing

- llrt_core/src/modules/http/request.rs
- tests/unit/http.test.ts
Add the following method to improve the compliance of `Request` object.
- Request.blob()
> feat: Improved compliance of Request object

- llrt/src/main.rs
- llrt_core/src/modules/buffer.rs
- llrt_core/src/modules/crypto/mod.rs
- llrt_core/src/modules/http/headers.rs
- llrt_core/src/modules/uuid.rs
- llrt_core/src/stream/writable.rs
- llrt_core/src/utils/object.rs
- llrt_core/src/vm.rs
- tests/unit/buffer.test.ts
- tests/unit/crypto.test.ts
https://github.com/awslabs/llrt/issues/421
Use shared array buffer rather than copy bytes 
> fix: buffer shared memory

- Cargo.lock
- llrt_core/Cargo.toml
- llrt_core/src/modules/xml.rs
> Upgrade quick-xml

- build.mjs
Related #439
Some of the things that should have been addressed by this PR were omitted.
`navigator` and `performance` should be removed as they no longer need to be excluded.
> fix: delete esbuild external option

- README.md
- build.mjs
- package.json
- yarn.lock
This PR makes it easy to perform multipart uploads of large files to Amazon S3 without any proprietary implementation.
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-lib-storage/
> feat: include @aws-sdk/lib-storage

- README.md
Adds documentation for all the environment variables defined in `llrt_core/src/environment.rs`.
> add documentation for environment variables

- Cargo.lock
- llrt_core/Cargo.toml
https://github.com/servo/rust-url/issues/952
There is a significant increase in size. We'll downgrade for now and update other dependencies
> Downgrade URL crate & update reps

- llrt_modules/Cargo.toml
- llrt_utils/src/lib.rs
before:
```rust
> cargo build --package=llrt_utils --no-default-features --target=wasm32-wasi
warning: patch for the non root package will be ignored, specify patch at the workspace root:
package:   /home/sumeet/llrt/llrt_core/Cargo.toml
workspace: /home/sumeet/llrt/Cargo.toml
warning: /home/sumeet/llrt/Cargo.toml: `panic` setting is ignored for `test` profile
Compiling llrt_utils v0.1.15-beta (/home/sumeet/llrt/llrt_utils)
error[E0433]: failed to resolve: use of undeclared crate or module `tokio`
--> llrt_utils/src/ctx.rs:9:5
|
9 | use tokio::sync::oneshot::{self, Receiver};
|     ^^^^^ use of undeclared crate or module `tokio`
error[E0599]: no method named `spawn` found for reference `&Ctx<'js>` in the current scope
--> llrt_utils/src/ctx.rs:39:14
|
39 |         self.spawn(async move { …
```
> fix llrt_utils build when `ctx` feature, which depends on tokio, is disabled

- llrt/src/main.c
Cold start performance is improved by memory mapping the in-memory file descriptor in the self-extracting executable file compressor.
This yields a 8%-20% performance improvement for a "hello world" lambda function
> perf: Mmap self extracting binary

- llrt_modules/Cargo.toml
- Chrono is now only enabled if need be, we should also provide a `time-rs` implementation since I personally don't use chrono
> Feature flag chrono

- llrt_modules/src/modules/process.rs
> Cleanup CWD function

- llrt_core/src/modules/console.rs
> llrt_core: add console.clear

- llrt/Cargo.toml
- llrt/src/main.rs
- llrt_core/Cargo.toml
> llrt: support windows build

- Cargo.lock
- llrt/Cargo.toml
- llrt/src/main.rs
Reverts awslabs/llrt#539
Before finding a fix, make sure the program is usable
> Revert "use mimalloc on windows"

- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Makefile
- llrt_core/build.rs
> Add ci support for windows

- Makefile
- README.md
- We have split the builds for `Lambda` and `Container` so that the desired binaries can be created quickly on a laptop PC.
- The README has been improved accordingly.
> chore: Improved binary creation method

- llrt_utils/Cargo.toml
- Fix missing feature for llrt_utils
> Fix build of llrt-utils

- .github/workflows/build-modules.yml
- llrt_modules/Cargo.toml
- Add CI for each feature
- Remove tokio full and use scoped features
- Relax versions for dependencies
> Improve features and CI

- Cargo.lock
- llrt_core/Cargo.toml
- llrt_core/src/modules/llrt/xml.rs
- llrt_core/src/modules/util/text_decoder.rs
- llrt_core/src/runtime_client.rs
- llrt_modules/Cargo.toml
- llrt_modules/src/modules/buffer.rs
- llrt_utils/Cargo.toml
- llrt_utils/src/encoding.rs
> Cleanup client

- CHANGELOG.md
- Cargo.lock
- llrt/Cargo.toml
- llrt_core/Cargo.toml
- llrt_modules/Cargo.toml
- llrt_utils/Cargo.toml
> Prepare v0.3.0-beta

- README.md
The execution example has been changed because it is more likely to work if the platform is bundled with the browser specification.
> fix: Improved examples of ESBUILD execution

- API.md
- Cargo.lock
- llrt_modules/Cargo.toml
- modules/llrt_os/Cargo.toml
- modules/llrt_os/src/lib.rs
- modules/llrt_os/src/network.rs
- modules/llrt_os/src/statistics.rs
- modules/llrt_os/src/unix.rs
- modules/llrt_os/src/windows.rs
- types/os.d.ts
Added most of the methods of the OS module.
- os.cpus()
- os.devNull
- os.endianness()
- os.freemem()
- os.getPriority()
- os.homedir()
- os.hostname()
- os.loadavg()
- os.machine()
- os.networkInterfaces()
- os.setPriority()
- os.totalmem()
- os.uptime()
- os.userInfo()
> feat: OS Module Improvements

- llrt/src/main.rs
- llrt_core/src/modules/mod.rs
- llrt_core/src/modules/repl.rs
- llrt_core/src/vm.rs
Adding a simple repl mode
https://nodejs.org/en/learn/command-line/how-to-use-the-nodejs-repl
https://github.com/DelSkayn/rquickjs/blob/master/examples/rquickjs-cli/src/main.rs
> support repl

- llrt_core/src/modules/js/@llrt/test/index.ts
When there is no test file in the test folder, output the test results directly
> test: handle no test file

- Cargo.lock
- libs/llrt_context/Cargo.toml
- libs/llrt_context/src/lib.rs
- libs/llrt_utils/src/object.rs
- libs/llrt_utils/src/primordials.rs
- llrt_core/src/module_builder.rs
- llrt_core/src/module_loader/mod.rs
- llrt_core/src/module_loader/require.rs
- llrt_core/src/modules/js/@llrt/test/index.ts
- llrt_core/src/modules/js/@llrt/test/worker.ts
- llrt_core/src/utils/clone.rs
- llrt_core/src/utils/ctx.rs
- llrt_core/src/utils/mod.rs
- llrt_core/src/vm.rs
- modules/llrt_exceptions/src/lib.rs
> Add more primordials

- llrt/src/minimal_tracer.rs
- llrt_core/src/runtime_client.rs
- modules/llrt_events/src/lib.rs
- modules/llrt_perf_hooks/src/lib.rs
https://github.com/awslabs/llrt/pull/698#issuecomment-2506306188
Applying fixes that occur with the new `cargo clippy`.
> chore: cargo clippy auto fix

- Makefile
- libs/llrt_utils/src/lib.rs
- libs/llrt_utils/src/reuse_list.rs
- llrt_core/src/modules/js/@llrt/test/SocketClient.ts
- llrt_core/src/modules/js/@llrt/test/index.ts
- llrt_core/src/modules/js/@llrt/test/worker.ts
- modules/llrt_child_process/src/lib.rs
- modules/llrt_events/src/lib.rs
- modules/llrt_net/src/server.rs
- modules/llrt_net/src/socket.rs
- modules/llrt_stream/src/readable.rs
- modules/llrt_stream/src/writable.rs
- tests/unit/child_process.test.ts
- tests/unit/compile.test.ts
- tests/unit/fetch.test.ts
- tests/unit/fs.test.ts
- tests/unit/http.test.ts
- tests/unit/path.unix.test.ts
- tests/unit/path.win.test.ts
- tests/unit/require.test.ts
> fix: Test runner timeout

- tests/unit/crypto.subtle.test.ts
Just a little improvement to the test code.
- Delete currently invalid test patterns
- Add available test patterns
> chore(crypto): update test code

- Cargo.lock
- llrt/src/repl.rs
- llrt_core/src/modules/console.rs
> chore: Update dependencies

- README.md
related #801 
- As part of the fetch refactor, we changed the behavior of environment variables, so we'll update the documentation accordingly.
- Other changes are due to new `make fix` specifications.
> chore(docs): update the description of the LLRT_HTTP_VERSION environment variable

- modules/llrt_fs/src/mkdir.rs
- tests/unit/fs.test.ts
https://github.com/awslabs/llrt/issues/824
Paths are now resolved before created.
> fix: mkdir path resolve

- modules/llrt_path/src/lib.rs
close: https://github.com/awslabs/llrt/issues/840
> fix #840: resolve supports paths starting with ..

- Cargo.lock
- linker/cc
- linker/cxx
- llrt/Cargo.toml
Sn malloc dependency upgrade fixes a bug upstream.
> chore: snmalloc dep upgrade

- llrt_modules/README.md
I struggled with setting up the llrt modules because docs were outdated. Now it works!
I have also included instructions for configuring the modules locally, as they have not yet been published as a crate.
> Update examples and docs in modules README.md

- libs/llrt_compression/Cargo.toml
- modules/llrt_crypto/Cargo.toml
- modules/llrt_crypto/src/lib.rs
- modules/llrt_http/src/lib.rs
- Make subtle Rust optional and prepare for C based implementation
- Fix HTTP compilation error for a subset of flags
- Relax zstd version
> Various fixes

- Cargo.lock
- llrt_core/src/modules/llrt/xml.rs
- modules/llrt_child_process/src/lib.rs
- modules/llrt_events/src/custom_event.rs
- modules/llrt_http/src/request.rs
- modules/llrt_url/src/url_class.rs
> chore(deps): Update dependencies

- modules/llrt_url/src/url_search_params.rs
I am migrating to llrt url implementation, so I brought over some tests.
> Adding rust tests for URLSearchParams

- Cargo.lock
- libs/llrt_dns_cache/Cargo.toml
- llrt_core/build.rs
- llrt_core/src/compiler.rs
> chore(deps): Update deps

- modules/llrt_fetch/src/request.rs
- tests/wpt/FileAPI.blob.test.ts
- wpt_errors.txt
- We updated it because the WPT results changed when I ran it with the latest commit.
- Other minor improvements have been made.
> chore(wpt): update wpt-errors

- Cargo.lock
- libs/llrt_numbers/Cargo.toml
- libs/llrt_numbers/benches/numbers.rs
- libs/llrt_numbers/src/lib.rs
- llrt_core/Cargo.toml
- modules/llrt_crypto/Cargo.toml
- modules/llrt_crypto/src/lib.rs
- modules/llrt_crypto/src/subtle/derive.rs
- modules/llrt_crypto/src/subtle/encryption.rs
- modules/llrt_crypto/src/subtle/export_key.rs
- modules/llrt_crypto/src/subtle/generate_key.rs
- modules/llrt_crypto/src/subtle/key_algorithm.rs
- modules/llrt_crypto/src/subtle/mod.rs
- modules/llrt_crypto/src/subtle/sign.rs
- modules/llrt_crypto/src/subtle/verify.rs
- modules/llrt_net/Cargo.toml
- modules/llrt_net/src/server.rs
- modules/llrt_net/src/socket.rs
- modules/llrt_path/Cargo.toml
- modules/llrt_path/benches/slash_replacement.rs
- tests/unit/crypto.subtle.test.ts
Updates crypto dependencies to latest versions. This includes massive performance boost of RSA encryption.
This PR also fixes some bugs for RSA encryption.
> Update and fix subtle.crypto

- Cargo.lock
- modules/llrt_crypto/Cargo.toml
Relaxing versions and update RS dependencies
> Relax and update Rust deps

- tests/wpt/FileAPI/support/Blob.js
- tests/wpt/common/get-host-info.sub.js
- tests/wpt/fetch.api.abort.test.ts
- tests/wpt/fetch.api.basic.test.ts
- tests/wpt/fetch.api.request.test.ts
- tests/wpt/fetch.harness.js
- tests/wpt/fetch/api/request/request-error.js
- tests/wpt/fetch/api/resources/utils.js
- wpt_errors.txt
The wpt harness and scripts have been modified to allow more tests to be run to resolve the issues.
> fix(wpt): modify to run more test cases

- API.md
- Cargo.lock
- build.mjs
- libs/llrt_compression/Cargo.toml
- libs/llrt_context/Cargo.toml
- libs/llrt_dns_cache/Cargo.toml
- libs/llrt_encoding/Cargo.toml
- libs/llrt_json/Cargo.toml
- libs/llrt_logging/Cargo.toml
- llrt_core/Cargo.toml
- llrt_modules/Cargo.toml
- modules/llrt_abort/Cargo.toml
- modules/llrt_async_hooks/Cargo.toml
- modules/llrt_child_process/Cargo.toml
- modules/llrt_console/Cargo.toml
- modules/llrt_crypto/Cargo.toml
- modules/llrt_dns/Cargo.toml
- modules/llrt_events/Cargo.toml
- modules/llrt_exceptions/Cargo.toml
- modules/llrt_fetch/Cargo.toml
- modules/llrt_fs/Cargo.toml
- modules/llrt_os/Cargo.toml
- modules/llrt_path/Cargo.toml
- modules/llrt_process/Cargo.toml
- modules/llrt_stream/Cargo.toml
- modules/llrt_url/Cargo.toml
- modules/llrt_zlib/Cargo.toml
- Linted Cargo.toml and removed unnecessary references.
- Fixed broken links and missing triple backquotes in API.md.
- Removed useless source map generation during build.
> chore: Minor cleaning
